<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/lib/bootstrap/js/bootstrap.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/lib/rainbow.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/lib/language/generic.js' ?>"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/CoreTheme/ShortCodes/lib/ShortCode-JS.js' ?>"></script>
<link href="<?php echo get_template_directory_uri() . '/CoreTheme/ShortCodes/lib/Shortcode-Css.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo get_template_directory_uri() . '/lib/bootstrap/css/bootstrap.min.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo get_template_directory_uri() . '/lib/bootstrap/css/bootstrap-responsive.min.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo get_template_directory_uri() . '/lib/themes/github.css' ?>" rel="stylesheet" type="text/css">
<script type="text/javascript">

jQuery(document).ready(function($){
});

</script>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#post" data-toggle="tab">Post Specific</a></li>
    <li><a href="#page" data-toggle="tab">Page Specific</a></li>
    <li><a href="#general" data-toggle="tab">General</a></li>
    <li><a href="#advanced" data-toggle="tab">Advanced</a></li>
  </ul>
  <div class="tab-content">
    <div id="post" class="tab-pane active">
    </div>
    <div id="page" class="tab-pane">
    
    </div>
    <div id="general" class="tab-pane">
    	<h1>Buttons</h1>
    	<p>
    	Buttons are used through out Aisis in the core theme and in the 
    	Admin Panel. The way you can use buttons is through this very simple
    	short code which will take a link and turn it into a button.
    	</p>
    	
    	<p><input type="button" onClick="button()" value="Insert This Shortcode!" 
    	class='btn btn-large btn-success'/></p>
    	
    	<p><h2>How To Use The Button:</h2></p>
    	
    	<pre>
    	<code data-language="generic">
    	[button size='' color='' link = 'link']Title[/button]
    	</code>
    	</pre>
    	
    	<p><h3>Allowed Options:</h3></p>
    	
    	<p class="text-info"><strong>Please Note:</strong>
    		We only support the bellow options as they are typed.
    		if you pass nothing in, we will create a regular button
    		with no styling applied to it.
    	</p>
    	
    	<p><h3>For size:</h3></p>
    	<p><a href="#" class="btn btn-large">large</a> 
    	<a href="#" class="btn btn-small">small</a> 
    	<a href="#" class="btn btn-mini">mini</a></p>
    	
    	<p><h3>For Colors</h3></p>
    	
    	<p><a href="#" class="btn btn-danger">red</a> 
    	<a href="#" class="btn btn-success">green</a> 
    	<a href="#" class="btn btn-primary">blue</a> 
    	<a href="#" class="btn btn-info">light-blue</a> 
    	<a href="#" class="btn btn-warning">yellow</a> 
    	<a href="#" class="btn btn-inverse">black</a></p>   		
    	
    	<p><h2>Insert Into Your Post!</h2></p>
    </div>
    <div id="advanced" class="tab-pane">
    	<h1>Marketing Page Layout!</h1>
    	<p>Aisis Comes with a set of short codes that are best used together and 
    	there is no better way to illustrate that then the marketing shortcodes.</p>
    	
    	<p class="text-info"><strong>Note:</strong> It is highly advised that you use
    	these short codes with eachother inconjunction with the button short code.
    	These set of short codes are meant and intended to be used as one.</p>
    	
    	<p><h2>JumboTron</h2></p>
    	<p>The first thing to do is to center the content and to do this we have
    	a jumbotron short code that you can insert into your post, between the tags
    	is where the magic begins.</p>
    	
    	<p><input type="button" onClick="jumbotron()" value="Insert This Shortcode!" 
    	class='btn btn-large btn-success'/></p>
    	
    	<pre>
    	<code data-language="generic">
    	[jumbotron]Content will go here[/jumbotron]
    	</code>
    	</pre>
    	
    	<p><h2>Marketing Title</h2></p>
    	
    	<p>The marketing title is best used with the jumbotron as it really makes the
    	title pop.</p>
    	
    	<p class="text-info"><strong>Note:</strong> It is suggested that your titles be
    	short and consise and that you use the marketing lead short code for longer descriptions.
    	</p>
    	
    	<p><input type="button" onClick="marketingTitle()" value="Insert This Shortcode!" 
    	class='btn btn-large btn-success'/></p>
    	
    	<pre>
    	<code data-language="generic">
    	[marketingTitle]This is my Title![/marketingTitle]
    	</code>
    	</pre>
    	
    	<p><h2>Marketing Lead</h2></p>
    	
    	<p>The marketing lead is a small description which essentially tells the reader
    	what it is you are trying to sell or what it is your marketing page is about.</p>
    	
    	<p><input type="button" onClick="marketingLead()" value="Insert This Shortcode!" 
    	class='btn btn-large btn-success'/></p>
    	
    	<pre>
    	<code data-language="generic">
    	[marketingLead]This is my Title![/marketingLead]
    	</code>
    	</pre>
    
    </div>
  </div>
</div>
