	<?php
    /**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is the default 404 Template for the 404.php file
	 *		in the theme it's self. This file is loaded via the
	 *		LoadTemplates.
	 *
	 *		Function used to load this file: aisis_404();
	 *		Can over write this function?: yes
	 *
	 *		@see Aisis->AisisCore->Templates->LoadTemplates
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 ?>	
     <div class="err"><?php echo aisis_404_err_message_banner(); ?></div>
    <div id="contentFull">
      <article class="post clearfix">
          <header>
              <h1 class="postTitle"><?php echo aisis_404_err_message(); ?></h1>
          </header>
          <h1>You may search again: </h1>
          <form method="get" id="404SearchForm" action="<?php echo home_url(); ?>/" >
              <input type="search" id="404Search" name="s" placeholder="Looking for?" />
              <input type="submit" id="submitSearch" />
          </form>
      </article>
      <!-- /.post -->
    
    </div>
    <?php aisis_footer(); ?>