<?php
    /**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is the default core look for the Author Template
	 *		used in Aisis via the is_author() call in the index.php
	 *		at the base of the theme (@package Aisis). This file
	 *		is loaded via the LoadTemplates.
	 *
	 *		Function used to load this file: aisis_author();
	 *		Can over write this function?: yes
	 *
	 *		@see Aisis->AisisCore->Templates->LoadTemplates
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 global $author, $wp_query;
	 
	 //Posts and author data
	 $curauth = $wp_query->get_queried_object();
	 $aisis_author_arguments = array('author' => $curauth->ID); 
	 $posts = query_posts($aisis_author_arguments);
?>    
  
    <div id="author">
        <article class="post clearfix">
            <header>
                <h1 class="postTitle"><?php echo $curauth->user_login; ?></h1>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="glossy post-image">
                   <?php echo get_avatar($curauth->user_email, 250);?>
                </figure>
            <?php } ?>
            <p><?php if ( $curauth->user_description != '' ){echo $curauth->user_description;}else{?>
            <?php deafualt_aisis_author_default_text(); } ?></p>
        </article>
    </div> 
       
    <div id="content">
    	<?php while(have_posts()) : the_post();?>
        <article class="post clearfix">
    
            <header>
                <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                <p class="postMeta"><time class="postDate" datetime="2011-05-08" pubdate><?php the_time('F, jS, Y'); ?></time> <em>in</em> <a href="#">Category</a></p>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail();?>
                </figure>
            <?php } ?>
            <?php the_content( __('<div class="readMore">More</div>', true)); ?>
        </article>
        <?php
			endwhile; 
		  	wp_reset_query(); 
		?>
    </div>
    <?php 
	get_sidebar();
    aisis_footer();
	?>