<?php
    /**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is used to set up the default Author Template.
	 *		That is, the template you see when viewing the Author's 
	 *		profile via clicking there name.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 global $wp_queryglobal, $current_user, $ID;
	
	 is_author_page();
?>    
    <div id="<?php author_id(); ?>">
        <article class="post clearfix">
            <header>
                <h1 class="postTitle"><?php echo get_the_author_meta('user_login', aisis_get_author_id()); ?></h1>
            </header>
                <figure class="glossy postImage">
                   <?php echo get_avatar( get_the_author_meta('user_email', aisis_get_author_id()), 300);?>
                </figure>
            <p>
				<?php
				if(get_the_author_meta('user_description', aisis_get_author_id()) != ''){
					echo get_the_author_meta('user_description', aisis_get_author_id());
				}else{
					aisis_author_default_text();
				}
                ?>
            </p>
        </article>
    </div> 