<?php
    /**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is used to set up the default Author Template.
	 *		That is, the template you see when viewing the Author's 
	 *		profile via clicking there name.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 global $author, $wp_query;
	 
	 //Posts and author data
	 $curauth = $wp_query->get_queried_object();
	 $aisis_author_arguments = array('author' => $curauth->ID); 
	 $posts = query_posts($aisis_author_arguments);
	 
	 //Options
	 $option_global = get_option('aisis_core_theme_setting_sidebar_global');
	 $options_slider_mini_global = get_option('aisis_core_theme_setting_slider_mini_global');
	
	//Do we display the slider mini?
	if($options_slider_mini_global['no_slider_mini_global'] != 1){
		aisis_header();
	}
?>    
    <div id="<?php if($option_global['no_sidebar_global'] != 1){echo 'author'; }else{ echo 'authorFull'; } ?>">
        <article class="post clearfix">
            <header>
                <h1 class="postTitle"><?php echo $curauth->user_login; ?></h1>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="glossy post-image">
                   <?php echo get_avatar($curauth->user_email, 250);?>
                </figure>
            <?php } ?>
            <p><?php if ( $curauth->user_description != '' ){echo $curauth->user_description;}else{?>
            <?php deafualt_aisis_author_default_text(); } ?></p>
        </article>
    </div> 
       
    <div id="<?php if($option_global['no_sidebar_global'] != 1){echo 'content'; }else{ echo 'contentFull'; } ?>">
    	<?php while(have_posts()) : the_post();?>
        <article class="post clearfix">
    
            <header>
                <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                <p class="postMeta"><time class="postDate" datetime="2011-05-08" pubdate><?php the_time('F, jS, Y'); ?></time> <em>in</em> <a href="#">Category</a></p>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail();?>
                </figure>
            <?php } ?>
            <?php the_content( __('<div class="readMore">More</div>', true)); ?>
        </article>
        <?php
			endwhile; 
		  	wp_reset_query(); 
		?>
    </div>
    <?php 
	if($option_global['no_sidebar_global'] != 1){
		get_sidebar();
	}
    aisis_footer();
	?>