<?php
    /**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is used for the is_category() check in the index.php
	 *		file at the base of the theme (@package Aisis). Loaded via
	 *		the LoadTemplates.
	 *
	 *		Function used to load this file: aisis_category();
	 *		Can over write this function?: yes
	 *
	 *		@see Aisis->AisisCore->Templates->LoadTemplates
	 *	
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
?>

	<div id="category">

		<article class="post clearfix">

			<header>
				<h1><?php single_cat_title(); ?></h1>
			</header>
			<p>
				<?php
                $category_id = get_query_var('cat');
                $category_name = get_category($category_id);
                if(category_description() != ''){
                    echo category_description();
                }else{ aisis_category_default_text();}
                $custom_query = new WP_Query('posts_per_page=-1&category_name='.$category_name->name);
                if ($custom_query->have_posts()) :
                    while ($custom_query->have_posts()) : $custom_query->the_post();
                        $posttags = get_the_tags();
                        if ($posttags) {
                            foreach($posttags as $tag) {
                                $all_tags[] = $tag->term_id;
                            }
                        }
                    endwhile;
                endif;
                if(!empty($all_tags)){
                    $tag_ids_unique = array_unique($all_tags);
                    foreach($tag_ids_unique as $tag_id) {
                        $post_tag = get_term( $tag_id, 'post_tag' );
                        if($tag_id != '' || $post_tag != ''){
                        echo '<a href="'.get_tag_link($tag_id).'">'.$post_tag->name.'</a>, ';
                        }else{
                            echo 'This category seems to have no tags.';
                        }
                    }
                }else{
                    echo 'This category seems to have no tags.';
                }
                        
                ?>
			</p>
		</article>
	</div>