<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is used to set up the category description
	 *		that sits above a list of posts in said category.
	 *		We get the title, the description (if set via WP or Aisis
	 *		options or a default one set by the hook) and we get the
	 *		tags for this category.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 $options = get_option('aisis_core');	 
?>

	<div id="<?php if($options['sidebar_index'] != 1 
	&& $options['sidebar_global'] != 1){echo 'category'; }else{ echo 'categoryFull'; } ?>">
		<article class="post clearfix">
			<header>
				<h1><?php single_cat_title(); ?></h1>
			</header>
			<p>
				<?php
                $category_id = get_query_var('cat');
                $category_name = get_category($category_id);
                if(category_description() != ''){
                    echo category_description();
                }else{ aisis_category_default_text();}
                $custom_query = new WP_Query('posts_per_page=-1&category_name='.$category_name->name);
                if ($custom_query->have_posts()) :
                    while ($custom_query->have_posts()) : $custom_query->the_post();
                        $posttags = get_the_tags();
                        if ($posttags) {
                            foreach($posttags as $tag) {
                                $all_tags[] = $tag->term_id;
                            }
                        }
                    endwhile;
                endif;
                if(!empty($all_tags)){
                    $tag_ids_unique = array_unique($all_tags);
                    foreach($tag_ids_unique as $tag_id) {
                        $post_tag = get_term( $tag_id, 'post_tag' );
                        if($tag_id != '' || $post_tag != ''){
                        echo '<a href="'.get_tag_link($tag_id).'">'.$post_tag->name.'</a>, ';
                        }else{
                            echo 'This category seems to have no tags.';
                        }
                    }
                }else{
                    echo 'This category seems to have no tags.';
                }
                        
                ?>
			</p>
		</article>
	</div>