<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file loads the default sidebar. This is the sidebar
	 *		that contians example, non working sidebar "widgets."
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */   
?>
    <div class="notice">
        Please <strong>note</strong> this sidebar is purley and example.
        It is advised you use the widgets provided by Aisis and WordPress
        to populate this sidebar. This is a fall back sidebar. You can optionaly
        use the Aisis Options to turn off the side bar gloably or for specific
        parts of the blog.
    </div>
    <br />
    <section class="widget">
        <h4 class="widgettitle">Example Sidebar</h4>
        <ul>
            <li><a href="<?php echo WPINC ?>/media.php?type=image&amp;TB_iframe=true" 
            title="add a caption to title attribute / or leave blank" class="thickbox">Example 1</a>   (3)</li>
            <li><a href="#">Design</a> (23)</li>
            <li><a href="#">Design </a>(18)</li>
        </ul>
    </section>
    <!-- /.widget -->
    
    <section class="widget clearfix">
        <h4 class="widgettitle">Example Flickr</h4>
        <script type="text/javascript" 
        src="http://www.flickr.com/badge_code_v2.gne?count=8.&display=latest&size=s&layout=x&source=user&user=52839779@N02">
        </script> 
    </section>
    <!-- /.widget -->
    
    <section class="widget">
        <h4 class="widgettitle">Example Pop Up Links</h4>
        <p>Click the following to see "Android like" notifications!</p>
        <ul>
            <li><a href="javascript:notice_one();">Notice One</a></li>
            <li><a href="javascript:notice_two();">Notice two</a></li>
            <li><a href="javascript:notice_three();">Notice three</a></li>
        </ul>
    </section>
    
    <section class="widget">
        <h4 class="widgettitle">Example Email Subscription</h4>
        <div class="formLayout">
            <p>Subscribe now!!</p>
            <form>
                <label>Email:</label> <input type="text" />
                <input type="submit" value="submit" />
            </form>
        </div>
    </section>