<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file loads the footer.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 $option_footer_bbpress = get_option('aisis_use_bbpress_footer_widget_setting');
?>
	<footer id="footer">
        <div class="footerWrapper">     
            <?php 
			if(($option_footer_bbpress['bbpress_footer'] == 1 && 'topic' == get_post_type()) || 
			($option_footer_bbpress['bbpress_footer'] == 1 && !empty($_GET['topic']))){
				if(function_exists('dynamic_sidebar') && dynamic_sidebar('bbpress_footer'));
			}else{
				if(function_exists('dynamic_sidebar') && dynamic_sidebar('Footer'));
			}?>
        </div>
        <div class="afterBlock">
            <div class="rightText"><?php aisis_default_right_footer_text(); ?></div>
            <div class="leftText"><?php aisis_default_left_footer_text(); ?></div>
        </div>
	</footer>
	
</div>
<?php wp_footer();?>
</body>
</html>