<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This is the footer for the Aisis Theme.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
?>

		</div>
        <footer id="footer">		
           <div class="footerWrapper">     
			   <?php if ( function_exists('dynamic_sidebar') && dynamic_sidebar('Footer') )?>
           </div>
           <div class="afterBlock">
           <div class="rightText"><?php aisis_default_right_footer_text(); ?></div>
           <div class="leftText"><?php aisis_default_left_footer_text(); ?></div>
  
           </div>
        </footer>

        <!-- /#footer --> 
        <?php wp_footer();?>
	</body>
</html>