<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file loads the footer.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 $options = get_option('aisis_core_bbpress');
	 aisis_var_dump($options);
?>
	<footer id="footer">
        <div class="footerWrapper">     
            <?php 
			if('forum' == get_post_type() || !empty($_GET['topic'])){
				if($options['bbpress_footer'] == 1 ){
					if(function_exists('dynamic_sidebar') && dynamic_sidebar('bbpress_footer'));
				}else{
					if(function_exists('dynamic_sidebar') && dynamic_sidebar('Footer'));
				}
			}else{
				if(function_exists('dynamic_sidebar') && dynamic_sidebar('Footer'));
			}?>
        </div>
        <div class="afterBlock">
            <div class="rightText"><?php aisis_default_right_footer_text(); ?></div>
            <div class="leftText"><?php aisis_default_left_footer_text(); ?></div>
        </div>
	</footer>
	
</div>
<?php wp_footer();?>
</body>
</html>