    
    <?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This is header slider which builds the slider for when you
	 *		make slides in the custom post type of 'slides'
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
	?>
	
	<?php
	$args = array( 'post_type' => 'slides');
	$loop = new WP_Query( $args );
	?>
    <div class="objectWrapper">
        <div class="flex-container">
          <div class="flexslider">
            <ul class="slides">
              <?php
                while($loop->have_posts()) : $loop->the_post();
              ?>
              <li>
                <?php the_content(); ?>
              </li>
              
              <?php endwhile;?>
              <li>test</li>
            </ul>
          </div>
        </div>
    </div>