    
    <?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This is header slider which builds the slider for when you
	 *		make slides in the custom post type of 'slides'
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
	 global $post;
	?>
	
	<?php
	$args = array( 'post_type' => 'slides');
	$loop = new WP_Query( $args );
	?>
    <?php if($loop->have_posts()){?>
        <div class="objectWrapper">
            <div class="flex-container">
              <div class="flexslider">
                <ul class="slides">
                  <?php
                    while($loop->have_posts()) : $loop->the_post();
                  ?>
                  <li>
                    <?php 
						echo get_post_meta($post->ID, 'aisis_slider_meta_box_desc', true);
						if(get_post_meta($post->ID, 'aisis_slider_meta_box_short_desc', true)){
							echo "<p class='flex-caption'>";
							echo get_post_meta($post->ID, 'aisis_slider_meta_box_short_desc', true);	
							echo "</p>";
						}
					?>
                  </li>
                  <?php endwhile;?>
                </ul>
              </div>
            </div>
        </div>
    <?php }?>
	
    <?php 
	$post_type = array('post_type' => 'mini', '&order'=>'DESC');
	$loop_mini = new WP_Query($post_type);
	?>
    <?php if($loop_mini->have_posts()){?>
    <div id="miniFeedWrapper">
    	<?php while ($loop_mini->have_posts()) : $loop_mini->the_post();?>
    	<div class="miniFeed">
        	<div class="title">
            <?php echo get_the_title();?>
            </div>
            <p><?php echo get_post_meta($post->ID, 'aisis_content_desc', true);?></p>
            <div class="readMoreBox">
            	<a href="<?php echo get_post_meta($post->ID, 'aisis_content_link', true);?>">Read More</a>
            </div>
        </div>
        <?php endwhile; ?>                   
    </div>
   	<?php } ?>