<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file deals with the slider and the mini feeds.
	 *		This file, while loaded through BuildAisisTheme
	 *		is used in other template files and checked for, if it should
	 *		load above those, by options that are set in the Aisis Options
	 *		Panel.
	 *
	 *		We deal with both the Slider and the Mini Feed here. Please
	 *		make sure that if you are over rideing this file that you take
	 *		both into consideration.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 global $post; 
?>
	
	<?php
	//Slider Code bellow.
	$args = array( 'post_type' => 'slides');
	$loop = new WP_Query( $args );
	?>
    <?php if($loop->have_posts()){?>
        <div class="objectWrapper">
            <div class="flex-container">
              <div class="flexslider">
                <ul class="slides">
                  <?php
                    while($loop->have_posts()) : $loop->the_post();
                  ?>
                  <li>
                    <?php 
						echo get_post_meta($post->ID, 'aisis_slider_meta_box_desc', true);
						if(get_post_meta($post->ID, 'aisis_slider_meta_box_short_desc', true)){
							echo "<p class='flex-caption'>";
							echo get_post_meta($post->ID, 'aisis_slider_meta_box_short_desc', true);	
							echo "</p>";
						}
					?>
                  </li>
                  <?php endwhile;?>
                </ul>
              </div>
            </div>
        </div>
    <?php }?>
	
    <?php 
	//MiniFeed Code bellow.
	$post_type = array('post_type' => 'mini');
	$loop_mini = new WP_Query($post_type);
	?>
    <?php if($loop_mini->have_posts()){?>
    <div id="miniFeedWrapper">
    	<?php while ($loop_mini->have_posts()) : $loop_mini->the_post();?>
    	<div class="miniFeed">
        	<div class="title">
            <?php echo get_the_title();?>
            </div>
            <p><?php echo get_post_meta($post->ID, 'aisis_content_desc', true);?></p>
            <div class="readMore">
            	<a href="<?php echo get_post_meta($post->ID, 'aisis_content_link', true);?>">Read More</a>
            </div>
        </div>
        <?php endwhile; ?>                   
    </div>
   	<?php } ?>