	<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This is the core index page that loads all the users posts
	 *		and displays them on the home page.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
	 
	 $options = get_option('aisis_core_theme_setting_sidebar_index');
	 $option_global = get_option('aisis_core_theme_setting_sidebar_global');
	 $options_slider_mini_global = get_option('aisis_core_theme_setting_slider_mini_global');
	 $options_slider_mini = get_option('aisis_core_theme_setting_slider_mini_index');
	 
	 if($options_slider_mini_global['no_slider_mini_global'] != 1 && $options_slider_mini['no_slider_mini_index'] != 1 && !is_category()){
		aisis_slider_mini();
	 }
	 
	 $aisis_category_list_options = array(
		  'orderby' => 'name',
		  'style' => 'none',
		  'title_li'=> '',
	  );
	 ?>	
     <div id="contentWrapper">
         
            <?php while(have_posts()) : the_post() ?>
            <article class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'post clearfix'; }else{ echo 'postFull clearfix'; }?>">
                <header>
                    <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                    <div class="post-comments"><?php comments_number('0', '1', '%'); ?> comments</div>
                    <div class="whoWrote">Author of this post:  <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>"><?php the_author_meta('display_name'); ?></a></div>
                    <div class="dateWrote"><?php the_time('F, jS, Y'); ?></div>
                    <div class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'headlineLine'; }else{ echo 'headlineLineFull'; }?>"></div>
                    <div class="infoOnPost"></div>
                </header>
                <div class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'imgPost'; }else{ echo 'imgPostFull'; }?>">
                    <?php if(has_post_thumbnail()){
                    ?>
                    <figure class="soft-embossed post-image">
                        <?php the_post_thumbnail(); ?>
                    </figure>
                    <?php } ?>
                </div>
                <?php the_content( __('<div class="readMore">More</div>', true)); ?>
          </article>
          <?php endwhile; ?>
          <?php global $wp_query; $total_pages = $wp_query->max_num_pages; if($total_pages > 1){?>
          <div class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'pagnation'; }else{ echo 'pagnationFull'; }?>">
       	 	<div class="prevPost"><?php previous_posts_link(__( 'Next', 'aisis' )) ?></div>
        	<div class="nextPost"><?php next_posts_link(__( 'Previous', 'aisis' )) ?></div>
    	  </div>
          <?php }?>

    </div>
    <?php 
	if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){
		get_sidebar();
	}
	?>
	 
     