<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is responsible for displaying a single
	 *		article and essay post (AE) from the Custom Post Type
	 *		Articles and Essay (AE).
	 *
	 *		By defeault we do not show the slider or the minifeed.
	 *		we also do not show the side bar as the purpose of this
	 *		custom post type is to show the content.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 	global $more, $post;
		
		$options_slider_mini_global = get_option('aisis_core_theme_setting_slider_mini_global');
		$options_slider_mini_single = get_option('aisis_core_theme_setting_slider_mini_single');
		
		$aisis_category_list_options = array(
				'orderby' => 'name',
				'style' => 'none',
				'title_li'=> '',
		);
		
		if($options_slider_mini_global['no_slider_mini_global'] != 1 && $options_slider_mini_single['no_slider_mini_single'] != 1){
			aisis_header();
		}				
?>
	 
    <div id="contentFull">
    	<?php while(have_posts()) : the_post();?>
        <article class="post clearfix">
    
            <header>
                <h1 class="postTitle"><?php the_title(); ?></h1>
                <div class="authorInfo">Author of this post: 
                <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
				<?php the_author_meta('display_name'); ?></a></div>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail();?>
                </figure>
            <?php } ?>
             <?php the_content(); ?>
        </article>
        <?php
			endwhile; 
		?>
    </div>
    
    <?php
    if('open' == $post->comment_status){
	    comments_template('', true);
    }
	aisis_footer();
	?>