<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		The goal here is to build the articles and essays index
	 *		based off the options that the user choses through the 
	 *		options panel.
	 *
	 *		@see AisisCore->Templates->TemplateBuilder->Build-Aisis-Theme
	 *		@see AisisCore->Templates->TemplateBuilder->Build-AE-Index		
	 *
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */	
	
	build_ae_index();
	
		 
?>

