<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		The goal here is to build the index based on the options
	 *		the user has passed in for both sidebar and layout.	
	 *
	 *		@see AisisTemplateBuilder
	 *		@see AisisAEIndex
	 *
	 *		@author:  Adam Balan
	 *		@version: 1.2
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */	
	
	$mini_feed_ae = new AisisMiniFeed('aisis_core');
	$mini_feed_ae->ae_page_mini_feed();
	
	$index = new AisisAeIndex('aisis_core');
	$index->build_ae_index();
?>
