<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		We load the index for the Articles and Essays. This file is loaded
	 *		via the BuildAisisTheme and then used in the ArchiveAEPage.php
	 *		file to load the loop of posts relating to this custom post type.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */	
	 
	$option_sidebar_index = get_option('aisis_core_theme_setting_sidebar_index');
	$option_sidebar_global = get_option('aisis_core_theme_setting_sidebar_global');
	$option_ae_layout = get_option('aisis_ae_design_setting');
	
	$aisis_query= array(
		'post_type' => 'ae',
		'paged' => $aisis_page_articles_essays
	);
	
	query_posts($aisis_query);	
	
	if($options_slider_mini_global['no_slider_mini_global'] != 1 && $options_slider_mini['no_slider_mini_index'] != 1){
	   aisis_header();
	}	 
	 
	aisis_var_dump($option_ae_layout['layout'], true); 
?>

	<?php if($option_ae_layout['layout'] == 1 || $option_ae_layout['layout'] == ''){?>
	<div id="<?php if($option_sidebar_index['no_sidebar_index'] != 1 && $option_sidebar_global['no_sidebar_global'] != 1)
	{ echo 'content'; }else{ echo 'contentFull'; }?>">
    	<?php while(have_posts()) : the_post();?>
    	<article class="post clearfix">
        	<header>
            	<h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                <div class="authorInfo">
                Author of this post:
                <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
				<?php the_author_meta('display_name'); ?></a>
                </div>
            </header>
            <?php if(has_post_thumbnail()){?>
            <div id="postImg">
            	<figure class="postImage soft-embossed">
                	<?php the_post_thumbnail();?>
                </figure>
            </div>
            <?php }
			the_excerpt(); 
			?>
        </article>
        <?php endwhile; ?>
    </div>	 
    <?php 
	if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){
		get_sidebar();
	}
	}elseif($option_ae_layout['layout'] == 2){ 
        if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){
            get_sidebar();
        }
		
		while(have_posts()) : the_post();	
		?>
        <div id="<?php if($option_sidebar_index['no_sidebar_index'] != 1 && $option_sidebar_global['no_sidebar_global'] != 1)
        { echo 'content'; }else{ echo 'contentFull'; }?>">
            <article class="post clearfix">
                <header>
                    <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                    <div class="authorInfo">
                    Author of this post:
                    <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
                    <?php the_author_meta('display_name'); ?></a>
                    </div>
                </header>
                <?php if(has_post_thumbnail()){?>
                <div id="postImg">
                    <figure class="postImage soft-embossed">
                        <?php the_post_thumbnail();?>
                    </figure>
                </div>
                <?php }
                the_excerpt(); 
                ?>
            </article>
        </div>	 
        <?php 
		endwhile;
	}elseif($option_ae_layout['layout'] == 3){ ?>
        <div id="<?php if($option_sidebar_index['no_sidebar_index'] != 1 && $option_sidebar_global['no_sidebar_global'] != 1)
        { echo 'contentNoBack'; }else{ echo 'contentNoBackFull'; }?>">
            <?php while(have_posts()) : the_post();?>
            <article class="post clearfix">
                <header>
                    <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                    <div class="authorInfo">
                    Author of this post:
                    <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
                    <?php the_author_meta('display_name'); ?></a>
                    </div>
                </header>
                <?php if(has_post_thumbnail()){?>
                <div id="postImg">
                    <figure class="postImage soft-embossed">
                        <?php the_post_thumbnail();?>
                    </figure>
                </div>
                <?php }
                the_excerpt(); 
                ?>
            </article>
            <?php endwhile; ?>
        </div>	 
        <?php 

        if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){
            get_sidebar();
        }    
	}
	global $wp_query; $total_pages = $wp_query->max_num_pages; if($total_pages > 1){?>
    <div class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1)
	{ echo 'pagnation'; }else{ echo 'pagnationFull'; }?>">
      <div class="prevPost"><?php previous_posts_link(__( 'Next', 'aisis' )) ?></div>
      <div class="nextPost"><?php next_posts_link(__( 'Previous', 'aisis' )) ?></div>
    </div>
    <?php }
	aisis_footer();
	?>