<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		Builds the index based off of layout and sidebar options.
	 *
	 *		@see AisisIndex
	 *		@see AisisTemplateBuilder
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.2
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */

	$index_mini = new AisisMiniFeed('aisis_core');
	$index_mini->index_post_page_mini_feed();

	$index = new AisisIndex('aisis_core');
	$index->build_aisis_index();
?>