<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is responsible for displaying a single
	 *		article and essay post (AE) from the Custom Post Type
	 *		Articles and Essay (AE).
	 *
	 *		By defeault we do not show the slider or the minifeed.
	 *		we also do not show the side bar as the purpose of this
	 *		custom post type is to show the content.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 	global $more, $post;
		$more = 0; //declare and set $more before The Loop
		
	 	$options = get_option('aisis_core_theme_setting_sidebar_single');
		$option_global = get_option('aisis_core_theme_setting_sidebar_global');
		$options_slider_mini_global = get_option('aisis_core_theme_setting_slider_mini_global');
		$options_slider_mini = get_option('aisis_core_theme_setting_slider_mini_single');
		$options_recent_posts = get_option('aisis_display_related_posts_setting');
		$options_cat_tags = get_option('aisis_display_categories_tags_setting');
		
		$aisis_category_list_options = array(
				'orderby' => 'name',
				'style' => 'none',
				'title_li'=> '',
		);		
?>
	 
    <div id="contentFull">
    	<?php while(have_posts()) : the_post();?>
        <article class="post clearfix">
    
            <header>
                <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                <p class="postMeta"><time class="postDate" datetime="2011-05-08" pubdate><?php the_time('F, jS, Y'); ?></time> <em>in</em> <a href="#">Category</a></p>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail();?>
                </figure>
            <?php } ?>
             <?php the_content(); ?>
        </article>
        <?php
			endwhile; 
		  	wp_reset_query(); 
		?>
        <!-- /.post -->
    
    </div>
    
    <?php
    if('open' == $post->comment_status){
	    comments_template('', true);
    }
	aisis_footer();
	?>