	<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This is what loads a single post and associated comments
	 *		for a user when they click on the title to the post on
	 *		the index page where all the posts are displayed.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
	 	global $more, $post;
		$more = 0; //declare and set $more before The Loop
	 	$options = get_option('aisis_core_theme_setting_sidebar_single');
		$option_global = get_option('aisis_core_theme_setting_sidebar_global');
		
		$options_slider_mini_global = get_option('aisis_core_theme_setting_slider_mini_global');
		$options_slider_mini = get_option('aisis_core_theme_setting_slider_mini_single');
		$options_recent_posts = get_option('aisis_display_related_posts_setting');
		$options_cat_tags = get_option('aisis_display_categories_tags_setting');
		$aisis_category_list_options = array(
				'orderby' => 'name',
				'style' => 'none',
				'title_li'=> '',
		);
		
		if($options_slider_mini_global['no_slider_mini_global'] != 1 && $options_slider_mini['no_slider_mini_single'] != 1){
			aisis_slider_mini();
		}
		
		if(is_sticky()){	
	 ?>	
    <div id="contentWrapper">
            <?php while(have_posts()) : the_post(); ?>
            <article class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'stickyPost'; }else{ echo 'stickyPostFull'; } ?> clearfix">
                <header>
                    <h1 class="post-title"><?php the_title(); ?></h1>
                    <div class="post-comments"><?php comments_number('0', '1', '%'); ?> comments</div>
                    <div class="whoWrote">Author of this post: <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>"><?php the_author_meta('display_name'); ?></a></div>
                    <div class="dateWrote"><?php the_time('F, jS, Y'); ?></div>
                    
                    <div class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'headlineLine'; }else{ echo 'headlineLineFull'; }?>"></div>				
                    
                    <div class="infoOnPost"></div>
                </header>
                <p>
                    <?php the_content(); ?>
                </p>
            <div class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'post-author'; }else{ echo 'post-author-full'; }?>">
            <h1><?php the_author()?></h1>
                <p><?php if ( get_the_author_meta( 'description' ) ){the_author_meta( 'description' );}else{?>
                <?php aisis_loop_single_author_blurb_default(); }?></p>
                <p>This author has written: <?php echo number_format_i18n( get_the_author_posts() ); ?> posts.</p>
            </div> 
            <?php if($options_cat_tags['cat_tags'] != 1){?>
            <div class="listCategories">Categories: <?php wp_list_categories($aisis_category_list_options);?></div> 
            <div class="listTags"><?php the_tags();?></div> 
            <?php } ?> 
          </article>
          <?php endwhile; ?>
          <?php global $wp_query; $total_pages = $wp_query->max_num_pages; if($total_pages > 1){?>
          <div class="prevPost"><?php previous_post_link('%link','%title' ) ?></div>
          <div class="nextPost"><?php next_post_link( '%link', '%title' ) ?></div>
          <?php }
		 if('open' == $post->comment_status){
			 comments_template('', true);
		 }
		?> 
     </div>  	
    <?php 
		}elseif(has_post_format('aside')){
	?>
    <div id="contentWrapper">
            <?php while(have_posts()) : the_post(); ?>
            <article class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'post clearfix'; }else{ echo 'postFull clearfix'; } ?>">
                <header>
                    <h1 class="post-title"><?php the_title(); ?></h1>
                    <div class="post-comments"><?php comments_number('0', '1', '%'); ?> comments</div>
                    <div class="whoWrote">Author of this post: <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>"><?php the_author_meta('display_name'); ?></a></div>
                    <div class="dateWrote"><?php the_time('F, jS, Y'); ?></div>
                    <div class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'headlineLine'; }else{ echo 'headlineLineFull'; }?>"></div>
                    <div class="infoOnPost"></div>
                </header>
                <p>
                    <?php the_content(); ?>
                </p>
				<?php if($options_cat_tags['cat_tags'] != 1){?>
                <div class="listCategories">Categories: <?php wp_list_categories($aisis_category_list_options);?></div> 
                <div class="listTags"><?php the_tags();?></div> 
            <?php } ?> 
          </article>
          <?php endwhile; ?>
          <?php global $wp_query; $total_pages = $wp_query->max_num_pages; if($total_pages > 1){?>
          <div class="prevPost"><?php previous_post_link('%link','%title' ) ?></div>
          <div class="nextPost"><?php next_post_link( '%link', '%title' ) ?></div>
          <?php } ?>
        <?php
			   if('open' == $post->comment_status){
				   comments_template('', true);
			   }
		?> 
     </div>      
    <?php	
		}else{
	?>
    <div id="contentWrapper">
            <?php while(have_posts()) : the_post(); ?>
            <article class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'post clearfix'; }else{ echo 'postFull clearfix'; } ?>">
                <header>
                    <h1 class="post-title"><?php the_title(); ?></h1>
                    <div class="post-comments"><?php comments_number('0', '1', '%'); ?> comments</div>
                    <div class="whoWrote">Author of this post: <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>"><?php the_author_meta('display_name'); ?></a></div>
                    <div class="dateWrote"><?php the_time('F, jS, Y'); ?></div>
                    <div class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'headlineLine'; }else{ echo 'headlineLineFull'; }?>"></div>
                    <div class="infoOnPost"></div>
                </header>
                <p>
                    <?php the_content(); ?>
                </p>
			<?php if($options_recent_posts['related_posts']){ ?>
          	<div class="relatedPosts">
          		<h2>Related Posts</h2>
				<?php
				$related = get_posts( array( 'category__in' => wp_get_post_categories($post->ID), 'numberposts' => 5, 'post__not_in' => array($post->ID) ) );
				if( $related ) foreach( $related as $post ) {
				setup_postdata($post); ?>
				 <ul> 
				   <li>
				     <a href="<?php the_permalink() ?>" rel="bookmark" title="<?php the_title(); ?>"><?php the_title(); ?></a>
				   </li>
				 </ul>   
				<?php }
				wp_reset_postdata(); ?>
          	</div>
          	<?php }?>
            <div class="<?php if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){echo 'post-author'; }else{ echo 'post-author-full'; }?>">
            <h1><?php the_author()?></h1>
                <p><?php if ( get_the_author_meta( 'description' ) ){the_author_meta( 'description' );}else{?>
                <?php aisis_loop_single_author_blurb_default(); }?></p>
                <p>This author has written: <?php echo number_format_i18n( get_the_author_posts() ); ?> posts.</p>
            </div>   
            <?php if($options_cat_tags['cat_tags'] != 1){?>
            <div class="listCategories">Categories: <?php wp_list_categories($aisis_category_list_options);?></div> 
            <div class="listTags"><?php the_tags();?></div> 
            <?php } ?>           
          </article>
          <?php endwhile; ?>
          <?php global $wp_query; $total_pages = $wp_query->max_num_pages; if($total_pages > 1){?>
          <div class="prevPost"><?php previous_post_link('%link','%title' ) ?></div>
          <div class="nextPost"><?php next_post_link( '%link', '%title' ) ?></div>
          <?php }
			   if('open' == $post->comment_status){
				   comments_template('', true);
			   }
		?> 
     </div>      
    <?php
		}
	if($options['no_sidebar_single'] != 1 && $option_global['no_sidebar_global'] != 1){
		get_sidebar();
	}
	 	
	?>
           