<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		We load the list of ALL posts here. This is your index.php
	 *		file essentially.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */	 
	 $options = get_option('aisis_core_theme_setting_sidebar_index');
	 $option_global = get_option('aisis_core_theme_setting_sidebar_global');
	 $options_slider_mini_global = get_option('aisis_core_theme_setting_slider_mini_global');
	 $options_slider_mini = get_option('aisis_core_theme_setting_slider_mini_index');
	 
	 $aisis_category_list_options = array(
		  'orderby' => 'name',
		  'style' => 'none',
		  'title_li'=> '',
	  );
	  
	if($options_slider_mini_global['no_slider_mini_global'] != 1 && $options_slider_mini['no_slider_mini_index'] != 1){
		aisis_header();
	}	  
?>

    <div id="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'content'; }else{ echo 'contentFull'; }?>">
    	<?php while(have_posts()) : the_post();?>
        <article class="post clearfix">
            <header>
                <h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                <p class="postMeta"><time class="postDate" datetime="2011-05-08" pubdate><?php the_time('F, jS, Y'); ?></time> <em>in</em> <a href="#">Category</a></p>
                Author of this post:  <a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>"><?php the_author_meta('display_name'); ?></a>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail();?>
                </figure>
            <?php } ?>
            <?php the_content( __('<div class="readMore">More</div>', true)); ?>
        </article>
        <?php
			endwhile; 
		  	wp_reset_query(); 
		?>
        <!-- /.post -->
    
    </div>
    <?php 
	if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){
		get_sidebar();
	}
	aisis_footer();
	?>
