 <?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This is what is displayed for a page. When a user creates
	 *		a new page this template is used.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
	 global $page_title, $post;
	 $options = get_option('aisis_core_theme_setting_sidebar_page');
	 $option_global = get_option('aisis_core_theme_setting_sidebar_global');
	 
	 if($options_slider_mini_global['no_slider_mini_global'] != 1 && $options_slider_mini['no_slider_mini_page'] != 1){
		 aisis_slider_mini();
	 }
 ?>
	 <?php if (have_posts()) : ?>
     <div id="contentWrapper">
            <article class="<?php if($options['no_sidebar_page'] != 1 &&  $option_global['no_sidebar_global']  != 1){ echo 'post clearfix'; }else{ echo 'postFull clearfix'; }?>">
                <?php
                 while (have_posts()) : the_post();
                    the_content();
                endwhile; 
                ?>
          </article>
     </div>
     <?php 
				if($options['no_sidebar_page'] != 1 && $option_global['no_sidebar_global'] != 1){
					get_sidebar();
				}
			   
			   if('open' == $post->comment_status){
				   comments_template('', true);
			   }
		   
		   endif;
    
     ?>