<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This file is responsible for loading what a single page looks
	 *		like. essentially this is your page.php.
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 global $page_title, $post;
	 
	 
	 if(is_front_page() && 'forum' != get_post_type()
	 && 'topic' != get_post_type()){
		 is_front_page_content();
	 }elseif(!is_front_page() && 'forum' != get_post_type() && 'topic' != get_post_type()){
		is_single_page();
	 }
	  
	 if('forum' == get_post_type() || 'topic' == get_post_type()){
		is_bbpress_forum();
	 }

?>  
    <div id="<?php content_id(); ?>">
    	<?php 
		while(have_posts()) : the_post();?>
        <article class="post clearfix">
            <header>
                <h1 class="postTitle"><?php the_title(); ?></h1>
            </header>
            <?php if(has_post_thumbnail()){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail();?>
                </figure>
            <?php } ?>
             <?php the_content(); ?>
        </article>
        <?php
			endwhile;  
		?>
        <!-- /.post -->  
    </div>
    
    <?php
	 sidebar_page();
	 
     if('open' == $post->comment_status){
	     comments_template('', true);
	 }
	 
     aisis_footer();
	?>