<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This is essentially what displays your search resaults. So
	 *		this is essentially your search.php
	 *
	 *		This file is loaded via the BuildAisisTheme file as
	 *		is loaded into a pluggable. This allows you to over
	 *		ride that function (which loads this file) in your custom
	 *		-functions.php Thus allowing you to change the way this page
	 *		looks by telling the function to load a different phtml file.
	 *
	 *		The same goal can be achieved in over writing this file
	 *		in a child theme or through Aisis Packages.
	 *
	 *		@see AisisCore->Templates->BuildAisisTheme
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 *
	 * =================================================================
	 */
	 global $post_id;
	 
	 $options = get_option('aisis_core_theme_setting_sidebar_search');
	 $option_global = get_option('aisis_core_theme_setting_sidebar_global');
	 if(have_posts()){
	?>
	<div id="<?php if($options['no_sidebar_search'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'content'; }else{ echo 'contentFull'; }?>">
   	<?php while (have_posts()) : the_post();?>
		<article class="post clearfix">
			<header>
				<h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
				<p class="postMeta"><time class="postDate" datetime="2011-05-08" pubdate><?php the_time('F, jS, Y'); ?></time> <em>in</em> <a href="#">Category</a></p>
			</header>
			<?php if(get_the_post_thumbnail($post_id) != ''){?>
                <figure class="soft-embossed post-image">
                    <?php the_post_thumbnail(); ?>
                </figure>
            <?php } ?>
			<p><?php the_excerpt(); ?></p>
		</article>
        <?php
		endwhile;
		?>
	</div>
    <?php 
	get_sidebar();
	aisis_footer();
	?>
    <?php
	 }else{
		 aisis_404();
	 }
	?>