 <?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		When a user searches for something, this template is called
	 *		to render out those resualts.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->Templates
	 * =================================================================
	 */
	 
	 global $post_id;
	 
	 $options = get_option('aisis_core_theme_setting_sidebar_index');
	 $option_global = get_option('aisis_core_theme_setting_sidebar_global');
 ?>
 <?php if(have_posts()){?>
 	<?php while (have_posts()) : the_post();?>
	<article class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'post clearfix'; }else{ echo 'postFull clearfix'; }?>">
            <header>
                <h1 class="post-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
                <div class="post-comments"><?php comments_number('0', '1', '%'); ?> comments</div>
                <div class="whoWrote">Author of this post: <?php the_author_link(); ?></div>
                <div class="dateWrote"><?php the_time('F, jS, Y'); ?></div>
                <div class="<?php if($options['no_sidebar_index'] != 1 && $option_global['no_sidebar_global'] != 1){ echo 'headlineLine'; }else{ echo 'headlineLineFull'; }?>"></div>
                <div class="infoOnPost"></div>
            </header>
            <div class="imgPost">
            	<?php if(get_the_post_thumbnail($post_id) != ''){
				?>
                <figure class="soft-embossed post-image">
                	<?php the_post_thumbnail(); ?>
                </figure>
                <?php } ?>
            </div>
            <p><?php the_excerpt(); ?></p>
            <div class="bottomLine"></div>
   </article>
    <?php endwhile; ?>
	<?php
 	}else{
		aisis_404();
	}?>