<?php
	 global $post;
	 
	 $options = get_option('aisis_core');
	 
	 $slides_loop = get_transient('loop');
	 if(!$slides_loop){
		 $slides_loop = header_slide_loop(); 
	 }
?>
	<?php if($options['slider_global'] != 1){
     	  	if($slides_loop->have_posts()){?>
        <div id="objectWrapper">
            <div class="flex-container">
              <div class="flexslider">
                <ul class="slides">
                  <?php
                    while($slides_loop->have_posts()) : $slides_loop->the_post();
                  ?>
                  <li>
                    <?php 
						echo get_post_meta($post->ID, 'aisis_slider_meta_box_desc', true);
						if(get_post_meta($post->ID, 'aisis_slider_meta_box_short_desc', true)){
							echo "<p class='flex-caption'>";
							echo get_post_meta($post->ID, 'aisis_slider_meta_box_short_desc', true);	
							echo "</p>";
						}
					?>
                  </li>
                  <?php endwhile;?>
                </ul>
              </div>
            </div>
        </div>
    <?php }
	}?>