<?php 
$attr = array(
	'align' => 'left',
	'class' => 'thumbnail imageRight',
	'width' => 350,
	'height' => 350
);

$args = array( 'post_type' => 'ae');
$ae = new WP_Query( $args );

if($ae->have_posts()){
	while($ae->have_posts()){
		$ae->the_post();
		?>
		<div class="post">
			<?php the_post_thumbnail('medium', $attr); ?>
			<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<p><?php the_excerpt(); ?></p>
		</div>
		<?php
	}
	
	?>
	<ul class="pager paddingBottom20">
	  <li class="previous">
	    <?php next_posts_link('&laquo; Older Entries'); ?>
	  </li>
	  <li class="next">
	  	<?php previous_posts_link('Newer Entries &raquo;'); ?>
	  </li>
	</ul><?php 
}
