<?php 
$cat_id = get_cat_ID( single_cat_title(null, false) );
query_posts( "cat=$cat_id&posts_per_page=10" );

$attr = array(
	'align' => 'left',
	'class' => 'thumbnail imageRight',
	'width' => 350,
	'height' => 350
);

if(have_posts()){
	while(have_posts()): the_post();
	?>
	<div class="post"><?php
		the_post_thumbnail('thumbnail', $attr); ?>
		<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
		<p><?php the_excerpt(); ?></p>
	</div>
		<?php
	endwhile;
}
?>