<?php
global $wp_query;

$attr = array(
		'align' => 'left',
		'class' => 'thumbnail imageRight',
		'width' => 350,
		'height' => 350
);

$post_query =  array ( 
	'post_type' => 'post',
);

$original_WP = $wp_query;
$wp_query = new WP_Query ( $post_query );

if($wp_query->have_posts()){
	while($wp_query->have_posts()){
		$wp_query->the_post();
		?>
		<div class="post">
			<?php the_post_thumbnail('medium', $attr); ?>
			<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<p><?php the_excerpt(); ?></p>
		</div>
		<?php
	}
	
	?>
	<ul class="pager paddingBottom20">
	  <li class="previous">
	    <?php next_posts_link('&laquo; Older Entries'); ?>
	  </li>
	  <li class="next">
	  	<?php previous_posts_link('Newer Entries &raquo;'); ?>
	  </li>
	</ul><?php 
}

$wp_query = $original_WP;