<?php 

$first_index =  array ( 'posts_per_page' => 3 );
$first_loop = new WP_Query ( $first_index );

$second_index =  array ( 'posts_per_page' => 3, 'offset' => 3 );
$second_loop = new WP_Query ( $second_index );

$third_index =  array ( 'posts_per_page' => 3, 'offset' => 6 );
$third_loop = new WP_Query ( $third_index );

?>
<div class="headLine">
	<h3>Get the latest news!!!</h3>
	<p>We will keep you in the loop....</p>
</div>

<div class="row">
<?php
if($first_loop->have_posts()){
	while ($first_loop->have_posts()) : $first_loop->the_post(); 
	?>
		<div class="span4 centered">
			<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<p><?php the_excerpt(); ?></p>
		</div>
	<?php
	endwhile;
}
?>
</div>
<div class="row">
<?php
if($second_loop->have_posts()){
	while ($second_loop->have_posts()) : $second_loop->the_post(); 
	?>	
		<div class="span4 centered">
			<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<p><?php the_excerpt(); ?></p>
		</div>
	<?php
	endwhile; 
}
?>
</div>
<div class="row">
<?php
if($third_loop->have_posts()){
	while ($third_loop->have_posts()) : $third_loop->the_post(); 
	?>
		<div class="span4 centered">
			<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<p><?php the_excerpt(); ?></p>
		</div>
	<?php
	endwhile; 
}
?>
</div>
<div class="span9 offset3 marginTop60 marginBottom20">
	<a href="#" class="btn btn-primary">See More Posts!</a>
	<a href="#" class="btn btn-success">Sign up today and Never Miss Out!</a>
</div>