<?php 
$tags = get_tags();
query_posts( "tag=".$tags[0]->name."&posts_per_page=10" );

$attr = array(
	'align' => 'left',
	'class' => 'thumbnail imageRight',
	'width' => 350,
	'height' => 350
);
?>

<?php 
if(have_posts()){
	while(have_posts()): the_post();
	?>
	<div class="post"><?php 
		the_post_thumbnail('medium', $attr); ?>
		<h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
		<p><?php the_excerpt(); ?></p>
	</div>	
		<?php
	endwhile;
}
?>