<?php 
$builder = AisisCore_Factory_Pattern::create('CoreTheme_Templates_Builder');

query_posts(array('nopaging' => 1));
$prev_year = null;

$attr = array(
	'align' => 'left',
	'class' => 'thumbnail imageRight',
	'width' => '350',
	'height' => '350'
);
?>
<div class="hero-unit">
	<h1><?php the_title(); ?></h1>
	<p><?php $builder->aisis_the_content(); ?></p>
</div>

<?php 
if ( have_posts() ) {
   while ( have_posts() ) {
      the_post();
      $this_year = get_the_date('Y');
      if ($prev_year != $this_year) {
          if (!is_null($prev_year)) {
             echo '</ul>';
          }
          echo '<div class="well headLine"> <h2>Year: ' . $this_year . '</h2>
          <p class="small">Bellow you will find all the posts related to this year!
          </p></div>';
      }
      ?>
      <div class="post">
      	<?php the_post_thumbnail('medium', $attr); ?>
      	<h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      	<p><?php the_excerpt(); ?></p>
      </div>
      <?php $prev_year = $this_year;
   }
}
?>