<?php 
global $post;

$carousel_active =  array ('post_type' => 'carousel', 'posts_per_page' => 1 );
$carousel_loop_active = new WP_Query ( $carousel_active );

$carousel =  array ('post_type' => 'carousel', 'offset' => 1);
$carousel_loop = new WP_Query ( $carousel );

if ($carousel_loop_active->have_posts()){
?>
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
		<?php while ($carousel_loop_active->have_posts()):
				$carousel_loop_active->the_post();?>
		<div class="item active">
			<img src="<?php echo $get_post_meta($post->ID, 'image', true); ?>" alt="">
			<div class="container">
				<div class="carousel-caption">
					<h1><?php echo the_title(); ?></h1>
					<p class="lead"><?php echo the_content(); ?></p>
					<a class="btn btn-large btn-primary" href="<?php echo $get_post_meta($post->ID, 'link', true); ?>"><
						?php echo $get_post_meta($post->ID, 'link_title', true); ?></a>
				</div>
			</div>
		</div>
		<?php endwhile; ?>
		<?php while ($carousel_loop->have_posts()):
				$carousel_loop->the_post();?>
		<div class="item">
			<img src="<?php echo $get_post_meta($post->ID, 'image', true); ?>" alt="">
			<div class="container">
				<div class="carousel-caption">
					<h1><?php echo the_title(); ?></h1>
					<p class="lead"><?php echo the_content(); ?></p>
					<a class="btn btn-large btn-primary" href="<?php echo $get_post_meta($post->ID, 'link', true); ?>"><
						?php echo $get_post_meta($post->ID, 'link_title', true); ?></a>
				</div>
			</div>
		</div>
		<?php endwhile; ?>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
​

<script type="text/javascript">
	jQuery(document).ready(function($) {
	    $('.carousel').carousel();
	});
</script>

<?php } ?>
