<?php 
global $post;

$carousel =  array ('post_type' => 'carousel' );
$carousel_loop = new WP_Query ( $carousel );

if($carousel_loop->have_posts ()){ ?>
	<div class="carousel slide">
		<div class="carousel-inner">
		<?php 
		while ( $carousel_loop->have_posts () ) :
					$carousel_loop->the_post ();
		?>
			<div class="item active">
				<?php the_post_thumbnail('full'); ?>
				<div class="container">
					<div class="carousel-caption">
						<h1><?php echo get_the_title(); ?></h1>
						<p class="lead"><?php echo the_content(); ?></p>
						<?php 
						$url = get_post_meta($post->ID, 'url', true);
						$link_title = get_post_meta($post->ID, 'link_title', true);
						if($url != '' && $link_title != ''){?>
						<a class="btn btn-large btn-primary" href="<?php echo $url; ?>"><?php echo $link_title; ?></a>
						<?php }?>
					</div>
				</div>
			</div>
		<?php endwhile; ?>	
		</div>
		<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
<?php }?>
