<?php 
global $post;

$caoursel_first_image = array('post_type' => 'carousel', 'posts_per_page' => 1);
$carousel_first_loop = new WP_Query($caoursel_first_image);


$carousel_images = array('post_type' => 'carousel', 'offset' => 1);
$carousel_images_loop = new WP_Query($carousel_images);
?>

<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
		<?php
		while ( $carousel_first_loop->have_posts () ) :
			$carousel_first_loop->the_post ();
			?>
		<div class="item active">
			<img src="<?php echo get_post_meta($post->ID, 'image', true); ?>"
				alt="" />
			<div class="container">
				<div class="carousel-caption">
					<h4>
					<?php the_title();?>
				</h4>
					<p>
					<?php the_content();?>
				</p>
					<a href="<?php echo get_post_meta($post->ID, 'link', true); ?>"
						class="btn btn-primary"> <?php echo get_post_meta($post->ID, 'link_text', true)?></a>
				</div>
			</div>
		</div>
		<?php 
	   	endwhile; 
	   	wp_reset_postdata();

	   	while ( $carousel_images_loop->have_posts() ) : 
	   	$carousel_images_loop->the_post();
	  	?>
		<div class="item">
			<img src="<?php echo get_post_meta($post->ID, 'image', true); ?>"
			alt="" />
			<div class="container">
				<div class="carousel-caption">
					<h4>
					<?php the_title();?>
				</h4>
					<p>
					<?php the_content();?>
				</p>
					<a href="<?php echo get_post_meta($post->ID, 'link', true); ?>"
						class="btn btn-primary"> <?php echo get_post_meta($post->ID, 'link_text', true)?></a>
				</div>
			</div>
		</div>
		<?php 
	   	endwhile; 
	   	wp_reset_postdata();
	  	?>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>