<?php
$template = AisisCore_Factory_Pattern::create('AisisCore_Template_Builder');
?>

<div class="jumbotron">
	<div class="container">
		<div class="caption">
			<h1>
				<?php
				if($template->get_specific_option('jumbo_title')){
					echo $template->get_specific_option('jumbo_title');
				}?>
			</h1>
			<p class="lead">
				<?php
				if($template->get_specific_option('jumbo_text')){
					echo $template->get_specific_option('jumbo_text');
				}?>
			</p>
			<p>
				<?php
				if($template->get_specific_option('jumbo_link')){
					echo '<a href="'.$template->get_specific_option('jumbo_link').'" class="btn btn-success">Find out more!</a>';
				}?>
			</p>			
		</div>
	</div>
</div>
