<?php 
global $post;

$mini_feed =  array ('post_type' => 'mini' );
$mini_loop = new WP_Query ( $mini_feed );

if ($mini_loop->have_posts()) {?>
<div class="container-narrow">
	<div class="row">
		<?php while ($mini_loop->have_posts()):
				$mini_loop->the_post();?>
		<div class="span4 marginTop">
			<img class="img-rounded" src="<?php echo get_post_meta($post->ID, 'image', true); ?>" />
			<h3><?php echo get_the_title(); ?></h3>
			<p><?php echo the_content(); ?></p>
			<p><a href="<?php echo get_post_meta($post->ID, 'link', true);?>" class="btn">
				<?php echo get_post_meta($post->ID, 'link_text', true); ?></a>
		</div>
		<?php endwhile; ?>
	</div>
</div>
<?php } ?>
