<?php 
global $posts;

$mini_feed =  array ('post_type' => 'mini' );
$mini_loop = new WP_Query ( $mini_feed );

if ($mini_loop->have_posts()) {?>
<div class="row">
	<?php while ($mini_loop->have_posts()):
			$mini_loop->the_post();?>
	<div class="span4 marginTop">
		<img class="img-circle" src="<?php echo get_post_meta($post->ID, 'image', true); ?>" />
		<h2><?php echo get_the_title(); ?></h2>
		<p><?php echo the_content(); ?></p>
		<p><a href="<?php echo get_post_meta($post->ID, 'link', true);?>" class="btn 
			<?php echo get_post_meta($post->ID, 'class', true);?>">Read More!</a>
	</div>
	<?php endwhile; ?>
</div>
<?php } ?>
