<?php 
	$menu_options = array(
		'menu' => 'main-menu',
        'menu_class' => 'nav',
       	'fallback_cb' => '',
        'menu_id' => 'main-menu',
        'walker' => new CoreTheme_NavWalker()
	);
	
	$search_form = array(
		'action' => home_url() . '/',
		'method' => 'GET',
		'class' => 'navbar-search pull-right'
	);
?>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="<?php echo home_url('/'); ?>" class="brand"><?php bloginfo('name'); ?></a>
      <div class="nav-collapse">
      	<div class="moveIcons">
      		<a href="#"><i class="icon-facebook iconSeperator"></i></a>
      		<a href="#"><i class="icon-twitter iconSeperator"></i></a>
      		<a href="#"><i class="icon-google-plus iconSeperator"></i></a>
      		<a href="#"><i class="icon-github iconSeperator"></i></a>
      		<a href="#"><i class="icon-likedin iconSeperator"></i></a>
      	</div>
		<?php 
		wp_nav_menu($menu_options); 
      	
      	$search = new CoreTheme_Templates_View_Form_NavSearch($search_form);
		echo $search;
      	?>
      </div>
    </div>
  </div>
</div>