<?php 
	$menu_options = array(
		'menu' => 'main-menu',
        'menu_class' => 'nav',
       	'fallback_cb' => '',
        'menu_id' => 'main-menu',
        'walker' => new CoreTheme_NavWalker()
	);
	
	$search_form = array(
		'action' => home_url() . '/',
		'method' => 'GET',
		'class' => 'navbar-search pull-right'
	);
?>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="<?php echo home_url('/'); ?>" class="brand"><?php bloginfo('name'); ?></a>
      <div class="nav-collapse">
      	<?php wp_nav_menu($menu_options); 
      	new CoreTheme_Templates_View_Form_NavSearch($search_form);
      	?>
      </div>
    </div>
  </div>
</div>