<?php 
$builder = new CoreTheme_Templates_Builder();
if(!$builder->sidebar('aisis_core', 'disable_sidebar') 
	&& !$builder->sidebar('aisis_core', 'disable_sidebar_posts')){
	?><div class="span6"><?php	
}else{
	?><div class="span12"><?php
}

global $post;
$thumb_nail_args = array(
	'align' => 'centered', 
	'class' => 'thumbnail marginBottom20 marginTop20'
);

if(have_posts()){
	while(have_posts()): the_post();
	?>
	<h1><?php the_title() ?></h1>
	<p>
		<em><strong>Written by: </strong>
			<a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
				<?php the_author_meta('display_name'); ?></a>
		</em>
	</p>
	<p><?php 
	the_post_thumbnail('full', $thumb_nail_args);
	the_content(); 
	?></p>
	<?php 
	endwhile;
	
	?>
	<ul class="pager paddingBottom20">
	  <li class="previous">
	    <?php next_post_link('%link'); ?>
	  </li>
	  <li class="next">
	  	<?php previous_post_link('%link'); ?>
	  </li>
	</ul><?php 
}

if('open' == $post->comment_status){
	comments_template();
}

?>
</div>