<div class="span6">
<?php 
$args = array('align' => 'centered', 'class' => 'thumbnail marginBottom20 marginTop20');

if(have_posts()){
	while(have_posts()): the_post();
	?>
	<h1><?php the_title() ?></h1>
	<p>
		<em><strong>Written by: </strong>
			<a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
				<?php the_author_meta('display_name'); ?></a>
		</em>
	</p>
	<p><?php 
	the_post_thumbnail('full', $args);
	the_content(); 
	?></p>
	<?php 
	endwhile;
}
?>
</div>