<div class="content">
	<?php
        $aisis_form = new AisisForm();
		$aisis_form->open_form(array(
			'method'=>'post',
			'action'=>'options.php?redirect_to=/wp-admin/admin.php?page=aisis-css-editor'
		));
	?>
    <div class="sideText">
        <h1>Custom Css Editor</h1>
        <p>Bellow you can enter in custom css to change the way the site looks. we will save this to your custom css
        file in your custom folder and also display the resaults here for future editing.<p>
        <p><?php create_submit(); ?></p>
    </div>
    <div class="alignForm">
		<?php
		do_settings_fields('aisis-css-editor','aisis_css_section');
		?>
    </div>
    <?php
	settings_fields('aisis-css-editor'); 
		$aisis_form->close_form();
		?>
</div>