<div class="content">
    <div class="sideText">
        <h1>Aisis Reset</h1>
        <p>You may reset the options table by clicking the reset options button. Doing so will
        cause all your previously set options to be reset back to the original defaults.</p>
        <div class="notice"><strong>Note:</strong> If you have bbpress installed and have set its options these will
        also be reset. If you are 100% sure, then please type 'reset' (with out quotes) and hit reset. 
        This is to make sure you are 100% sure.</div>
    </div>
    <p><?php create_reset_form(); ?></p>
</div>