<?php
$option = get_option('aisis_core');

$aisis_form = new AisisForm();
$aisis_update = new AisisUpdate();

if(!$aisis_update->check_for_udate_bool()){
	echo "<div class='success'>You are running the latest version of Aisis!</div>";
}
?>

<div class="content">
	<?php
	if(get_option('disable_update') != true){
        
		$aisis_form->open_form(array(
			'method'=>'post',
			'action'=>'options.php?redirect_to=/wp-admin/admin.php?page=aisis-core-update'
		));
	?>
            <div class="sideText">
                <h1>Aisis Core Update</h1>
                <p>You can choose bellow if you would like to have Aisis automatically check for, download
                and install updates for you.<p>
                <?php if(isset($option['update']) && $option['update'] == 1){?> <div class="notice">
                <strong>You have</strong> turned on silent auto update. 
                We will do the rest from here for you. Which includes downloading, installing and updating Aisis for you :D. </div><?php }?>
                <p><?php create_submit(); ?></p>
            </div>
            <div class="alignForm">
                <?php
                do_settings_fields('aisis-core-update','aisis_core_update_section');
                
                ?>
            </div>
            <?php
        settings_fields('aisis-core-update'); 
        $aisis_form->close_form();
	}
	
	if(!isset($option['update'])){

		if($_POST['check_me']){
			$aisis_update->get_latest_version_zip();
		}
		
		$aisis_form->open_form(array(
			'method'=>'post',
			'action'=>''
		));
		
		if($aisis_update->check_for_udate_bool()){	
			?>
            <div class="sideText">
                <h1>Aisis Update!</h1>
                <p><?php if($aisis_update->check_for_udate_bool()){
					?>Look like you have an update! Click the update button bellow to update Aisis to the latest version!<?php
				}else{
					?>You are all up to date with Aisis! Thats a good thing ya know!<?php	
				}?></p>
            </div>
            <div class="updateNotice"><strong>Update!!</strong> You have an update to the software waiting for you!
            Please note that you may need to click the update button twice inorder for it to work completely.
            </div><?php
			$aisis_form->create_aisis_form_element('input', array(
				'type' => 'submit',
				'value' => 'Update Aisis!',
				'name' => 'update_me',
				'class' => 'updateAisis'
			));
			
			$aisis_form->create_aisis_form_element('input', array(
				'type' => 'hidden',
				'value' => '1',
				'name' => 'check_me'
			));			
		}
		
		$aisis_form->close_form();
	}
	?>
</div>