<div class="sideText">
    <h1>Custom Text Options</h1>
    <p>Below you can enter in custom text for each of the sections.<br /><br />
    For sections like category or author you will note that each category can be given a description by default in WordPress, 
    as well as each author can have a bio. If neither of these are filled out, this text will display instead.
    <strong>p tags, blockquote tags, a tags, h1,2 and 3 tags.</strong></p>
    <div class="notice"><strong>Note:</strong> We use the WordPresss hooks 
    to display default content and display the content
    you create here. Please keep that in mind when over-riding the 
    <a href="http://aisis.adambalan.com/documentation/aisis-hooks/">Aisis Hooks</a>.</div>
    <p><?php create_submit(); ?></p>
</div>
<div class="alignForm">
	<?php do_settings_fields('aisis-core-options','aisis_custom_text_section'); ?>
</div>