<div class="sideText">
    <h1>Core Sidebar Options</h1>
    <p>Below are the options related to the sidebar. The changes you make will reflect on how the site
    and the site's content flows.</p>
    <p><?php create_submit(); ?></p>
</div>
<div class="alignForm">
	<?php
        do_settings_fields('aisis-core-options','aisis_sidebar_section');
        if(does_plugin_exist('bbpress/bbpress.php')){
            do_settings_fields('aisis-core-options', 'aisis_sidebar_bbpress_section');		
        }
    ?>
</div>