<div class="sideText">
    <h1>Core Sidebar Options</h1>
    <p>Bellow are the associated sidebar options for Aisis. These changes will reflect on
    your website upon hitting save.</p>
    <p><?php create_submit(); ?></p>
</div>
<div class="alignForm">
	<?php
        do_settings_fields('aisis-core-options','aisis_sidebar_section');
        if(does_plugin_exist('bbpress/bbpress.php')){
            do_settings_fields('aisis-core-options', 'aisis_sidebar_bbpress_section');		
        }
    ?>
</div>