<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This is the core look and feel for the entire admin section.
	 *		from here we load individual registered admin modules that
	 *		then add to this page based on what page the user is on.
	 *		
	 *		@author: Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 *
	 * =================================================================
	 */
	 
	//check theme version
	$aisis_check_version = new AisisUpdate();
	
	//Add the option for the update message
	add_option('admin_success_message', '', '', 'yes');	
	
	function create_submit(){
		$aisis_form = new AisisForm();
		return $aisis_form->create_aisis_form_element('input', array(
			'type'=>'submit',
			'value'=>'Save Your Choices!',
			'class'=>'jsEditorButton'
		));
	} 
?>
    <div id="top">
        <div class="title">
            Aisis Core Theme Options <?php echo $aisis_check_version->get_current_theme_version();?>
            <?php reset_aisis_options_form(); ?>
    	</div>
	</div>
       
	<?php
    check_for_aisis_messages();
    if(isset($_GET['page']) && $_GET['page'] == 'aisis-core-options'){
		$aisis_form = new AisisForm();
		$aisis_form->open_form(array(
			'method'=>'post',
			'action'=>'options.php?redirect_to=/wp-admin/admin.php?page=aisis-core-options'
		));
		?>
        <div id="coreTabs">
        	<ul>
            	<li><a href="#aisisCoreStyles">Core Config</a></li>
                <li><a href="#aisisSidebar">Sidebar Config</a></li>
                <li><a href="#aisisMiniFeed">MiniFeed(s) Config</a></li>
                <li><a href="#aisisCustomText">Default Text</a></li>
                <li><a href="#aisisSocial">Social Media Options</a></li>
            </ul>
            <div id="aisisCoreStyles">
            	<div class="content">
                	<?php aisis_site_design_options(); ?>
                </div>
            </div>
            <div id="aisisSidebar">
            	<div class="content">
            		<?php aisis_sidebar_options(); ?>
                </div>
            </div>
            <div id="aisisMiniFeed">
            	<div class="content">
                	<?php aisis_minifeed_options(); ?>
                </div>
            </div>
            <div id="aisisCustomText">
            	<div class="content">
                	<?php aisis_customtext_options(); ?>
            	</div>
            </div>
            <div id="aisisSocial">
            	<div class="content">
                	<?php aisis_social_media_options(); ?>
                </div>
            </div>            
        </div>
        <?php
		settings_fields( 'aisis-core-options' ); 
		$aisis_form->close_form();
    }
    else if(isset($_GET['page']) && $_GET['page'] == 'aisis-css-editor'){
       aisis_css_editor();
    }
    else if(isset ($_GET['page']) && $_GET['page'] == 'aisis-core-update'){
       aisis_update_page();
    }
    ?>
    
    </div>
    <script>
	/**
	 * Core functionality upon page load.
	 */
	$(function() {
		$( "#coreTabs" ).tabs();
		
		enableSideBar();
		$('#sidebar_global').click(enableSideBar)
		enableMini();
		$('#mini_global').click(enableMini)
		enableSlider();
		$('#slider_global').click(enableSlider)				
	});
	
	/**
	 * If the user has chosen to not show the
	 * the sidebar across the site keep the
	 * rest disabled.
	 */
	function enableSideBar(){
		if(this.checked){
			$('input.sidebar').attr("disabled", true);
		}
	}
	
	/**
	 * If the user has chosen to not show the
	 * the mini across the site, keep the other options
	 * disabled
	 */		
	function enableMini(){
		if(this.checked){
			$('input.mini').attr("disabled", true);
		}
	}
	
	/**
	 * If the user has chosen to not show the
	 * the slider across the site, keep the other options
	 * disabled
	 */
	function enableSlider(){
		if(this.checked){
			$('input.slider').attr("disabled", true);
		}
	}	
	
	/**
	 * This is used for the media uploader for when we are
	 * uploading images for the author banner.
	 */        
	jQuery(document).ready(function() {
		
		jQuery('#upload_image_button').click(function() {
			formfield = jQuery('#upload_image').attr('name');
			tb_show('', 'media-upload.php?type=image&TB_iframe=true');
			return false;
		});
	
		window.send_to_editor = function(html) {
			imgurl = jQuery('img',html).attr('src');
			jQuery('#upload_image').val(imgurl);
			tb_remove();
		}
		
		jQuery('#upload_aisis_header').click(function() {
			formfield = jQuery('#upload_image').attr('name');
			tb_show('', 'media-upload.php?type=image&TB_iframe=true');
			return false;
		});
		
		window.send_to_editor = function(html) {
			imgurl = jQuery('img',html).attr('src');
			jQuery('#aisis_header_img').val(imgurl);
			tb_remove();
		}
		
		var max = 10;
		jQuery(".alignForm label").each(function(){
			if($(this).width() > max){
				max = $(this).width();	
			}
		});
		jQuery(".alignForm label").width(max);
		
		$('.images').fancybox({
			openEffect: 'elastic',
			closeEffect: 'elastic',
			
			helpers:{
				title:{
					type: 'float'	
				}
			}
		});
	});	
	</script>