<div class="sideText">
    <h1>General Post Options</h1>
    <p>Below we give you the options to display or not display things such as categories and related posts for a post.</p>
    <p><?php create_submit(); ?></p>
</div>
<div class="alignForm">
	<?php
        do_settings_fields('aisis-core-options','general_post_options_section');
    ?>
</div> 
<div class="sideText">
    <h1>Image Header</h1>
    <p>Want to upload an image for the header? Select a image of size: 980x120 to use.</p>
</div>
<div class="alignForm">
	<?php
        do_settings_fields('aisis-core-options','image_header_section');
    ?>
</div> 
<div class="sideText">
    <h1>Colors</h1>
    <p>Bellow you can change the link and the H1, 2, 3 and 4 colors</p>
</div>
<div class="alignForm">
	<?php
        do_settings_fields('aisis-core-options','links_header_color_section');
    ?>
</div> 
<div class="sideText">
    <h1>Core Site Design</h1>
    <p>Below you can choose how you want the posts to display when a user is looking at the 
    general blog. Each  Image bellow repersents an example of how the site may look, in terms of how we list the posts.</p>
    <a id="admin_panel_image" href="<?php bloginfo('template_directory');?>/AisisCore/AdminPanel/images/ScreenShotPopUp.png" class="images" title="Full layout. No seperation.">
    <img src="<?php bloginfo('template_directory');?>/AisisCore/AdminPanel/images/ScreenShotPopUp.png" width="80" height="80" /></a>
    <a id="admin_panel_image" href="<?php bloginfo('template_directory');?>/AisisCore/AdminPanel/images/ScreenShotPopUp2.png" class="images" title="Seperate Boxes for each post.">
    <img src="<?php bloginfo('template_directory');?>/AisisCore/AdminPanel/images/ScreenShotPopUp2.png" width="80" height="80" /></a>
    <a id="admin_panel_image" href="<?php bloginfo('template_directory');?>/AisisCore/AdminPanel/images/ScreenShotPopUp3.png" class="images" title="No background at all.">
    <img src="<?php bloginfo('template_directory');?>/AisisCore/AdminPanel/images/ScreenShotPopUp3.png" width="80" height="80" /></a>
</div>
<div class="alignForm">
	<?php
        do_settings_fields('aisis-core-options','aisis_site_design_section');
    ?>
</div>
<?php if(does_plugin_exist('bbpress/bbpress.php')){ ?>
<div class="sideText">
    <h1>BBPress Options</h1>
    <p>We have some basic BBPress options that may affect how the user uss the forum part of the site.</p>
</div>
<div class="alignForm">
	<?php do_settings_fields('aisis-core-options','aisis_site_design_bbpress_section'); ?>
</div>
 <?php } ?>
