<?php

	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This file is used to display the update page and all the 
	 *		associated functions that go with it.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 * =================================================================
	 */

	$option = get_option('aisis_core_theme_setting_silent_update'); 
	if($option['turn_on_silent_update'] != 1){ 
		$silent_update = array('type' => 'submit', 'value'=>'Turn on silent update!', 'name'=>'defaults'); 
	}else{
		$silent_update = array('type' => 'submit', 'value'=>'Turn off silent update!', 'name'=>'defaults');
	}
	$aisis_update = new AisisUpdate();
	$aisis_form = new AisisForm();
?>
    <div class="content">
        <h1>Core Updator</h1>
        <p>You are on this page because you are looking to update the theme to the latest and greatest! Well Look no further we make this whole process very easy for you!</p>
    </div>
	<div class="content">
        	<div class="updateNotice">
            	This is the update page. You have the option to turn on <strong>Silent Auto Update</strong> which, when there is an update will automatically 
                update your system with out you ever knowing. <strong>Note:</strong> those who require to enter there ftp user and pass should not select Silent
                Auto Update.
            </div>
                <div class="alignForm">
                	
				<?php
				$aisis_form->open_form(array(
					'method'=>'post',
					'action'=>'options.php?redirect_to=/wp-admin/admin.php?page=aisis-core-options'
				));
				
				$aisis_form->create_aisis_form_element('label', array(
					'value'=>'Silent Auto Update Options. (On or Off)'
				));
				
				do_settings_fields('aisis-core-update', 'aisis_core_silent_update_section');
                $aisis_form->create_aisis_form_element('input',$silent_update);
                settings_fields( 'aisis-core-update' );
                
                $aisis_form->close_form();
				?>
                
                </div>
            	<div class="sideText">
                	<?php
					if($option['turn_on_silent_update'] != 1){
						if($aisis_update->check_for_udate_bool()){ ?>
						<h1>New Aisis-ness!</h1>
						<p>You are in for a real treat! There seems to be an update for Aisis! Lets update together
						and find out what kinds of epic sauce lies in wait!</p>
						<div class="smallNotice">Did you remember to back up your custom folder? Please do so before hitting the magic button bellow!
						Also please note: <strong>You may have to hit the update button again if your page refreshes and nothing happens</strong></div>
						<?php }else{?>
						<h1>Your Details</h1>
						<p>Bellow we have your current version and any other details you might want to know.</p>                   
						<?php
						}
					}else{
						?>
                        <h1>You Have Auto Update Turned on!</h1>
						<p>Bellow you will see what version you are running. This version may automatically change if there is a new update. Thats the whole point
                        of a Silent Auto Update :D</p> 
						<?php
					}?>
                </div>
        	<?php 
			if($option['turn_on_silent_update'] != 1){
				if(isset($_POST['upgrade'])){
					$aisis_update->get_latest_version_zip();
				}
				if($aisis_update->check_for_udate_bool()){
					$aisis_form->open_form(array(
						'method'=>'post',
						'action'=> admin_url('admin.php?page=aisis-core-update')
					));
					
					if(!$aisis_update->credential_check){
						$aisis_form->create_aisis_form_element('input', array(
							'type' => 'submit',
							'value' => 'Upgrade Now!',
							'name' => 'upgrade',
							'class' => 'bigUpgrade'
						));
					}
					
					$aisis_form->close_form();
					}else{
					echo "<div class='success'>You are currently running: <strong>" . $aisis_update->get_current_theme_version() . " Version</strong> of 
							the software! Check your site to see the latest changes! or check out 
					<a href=http://adambalan.com/aisis/VersionInfo.txt?keepThis=true&TB_iframe=true&height=650&width=650' class='thickbox' 
					title='Aisis Version Info'>Aisis Version Notes</a>!</div>";
				}
			}else{
					echo "<div class='success'>You are currently running: <strong>" . $aisis_update->get_current_theme_version() . " Version</strong> of 
												the software! Check your site to see the latest changes! or check out 
										<a href=http://adambalan.com/aisis/VersionInfo.txt?keepThis=true&TB_iframe=true&height=650&width=650' 
										class='thickbox' title='Aisis Version Info'>Aisis Version Notes</a>!</div>";				
			}?>                                                          
            </div>
        </div>