<?php

	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This is the Aisis Options page which allows you to set options
	 *		for the theme that are more basic then the editors where you can
	 *		edit various files.
	 *		
	 *		@author: Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 *
	 * =================================================================
	 */
	 
	 $aisis_form_element = new AisisForm();
	 
	 $basic_array_submit = array('value'=>'Save Your Work!', 'name'=>'defaults', 'class'=>'defaultText');
	 $facebook_save = array('value'=>'Link to Facebook!', 'name'=>'defaults');
	 $twitter_save = array('value'=>'Link to Twitter!', 'name'=>'defaults');
	 $tumblr_save = array('value'=>'Link to Tumblr!', 'name'=>'defaults');
	 $google_save = array('value'=>'Link to Google+!', 'name'=>'defaults');
	 $rss_save = array('value'=>'Link to RSS!', 'name'=>'defaults');
	 $core_options_save = array('value'=>'Save your Settings!', 'name'=>'defaults');
	 
	 $options = get_option('aisis_core_theme_setting_sidebar_global');
?>
<?php $aisis_forum_url = 'options.php?redirect_to=/wp-admin/admin.php?page=aisis-core-options' ?>
<form method="post" action="<?php echo $aisis_forum_url ?>">
<div id="coreTabs">
	<ul>
    	<li><a href="#aisisSidebarOptions">Aisis Sidebar Options</a></li>
        <li><a href="#aisisSliderMiniOptions">Aisis Slider and Mini Feed Options</a></li>
    	<li><a href="#aisisDefault">Aisis Default Text</a></li>
        <li><a href="#aisisSocial">Aisis Social Options</a></li>
        <li><a href="#aisisMisc">Misc. Options</a></li>
    </ul>
    <div class="bottom"></div>
    <div id="aisisSidebarOptions">
        <div class="content">
        	<h1>Sidebar?</h1>
            <p>We allow you to change where the side bar is displayed or even if the side bar is displayed at all. We
            give you granual controll over which pages (if any at all) that your sidebar shows up on. The page will then
            reszise to fit that new width.</p>
            <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $core_options_save);?></p>
        </div>
        <div class="content">
            <div class="alignForm">
                <div class="smallNotice">Selecting this will deactivate the other choices.</div>
                <label>click to remove the  Sidebar (Global)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_sidebar_global'); ?><br />
                <label>click to remove the Sidebar (Index)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_sidebar_index'); ?><br />
                <label>click to remove the Sidebar (Single)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_sidebar_single'); ?><br />
                <label>click to remove the Sidebar (Page)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_sidebar_page'); ?><br />                 
                <div class="smallNotice">By default we do not show the sidebar on a single Articles and Essays post.</div>
                <label>click to remove the Sidebar (Custom Index)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_sidebar_custom'); ?><br />                                                             
            </div>
        </div>
    </div>
    <div id="aisisSliderMiniOptions">
        <div class="content">
            <h1>Slider and Mini Feed?</h1>
            <p>We allow you to choose with pages, if any, the slider and the mini feed are displayed on. Much like the Sidebar Options we
            give you fine controll over where you want to displaye the slider and mini feeds.</p>
            <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?></p>
        </div>
		<div class="content">
        	<div class="notice">
            	Please note that the following will change the display for <strong>both</strong> the slider <strong>and</strong> the
                mini feeds.
            </div>
            <div class="alignForm">
                <label>click to remove the Slider and Mini Feed (Global)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_slider_mini_global'); ?><br />
                <label>click to remove the Slider and Mini Feed <br />
				(Index)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_slider_mini_index'); ?><br />
                <label>click to remove the Slider and Mini Feed (Single)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_slider_mini_single'); ?><br />
                <label>click to remove the Slider and Mini Feed <br />
				(Page)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_slider_mini_page'); ?><br />                 
                <div class="smallNotice">By default we do not show the slider and mini feed on a single Articles and Essays post.</div>
                <label>click to remove the Slider and Mini Feed (Custom Index)</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_core_theme_section_slider_mini_custom'); ?><br /> 
                 <br />                                                             
            </div>
        </div>        
    </div>
    <div id="aisisDefault">
        <div class="content">
            <h1>Change Default Text</h1>
            <p>Looking to change some of the default text and options through out the theme?
            Edit the information bellow to change the default text through out the site.</p>
            <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?></p>
        </div>
        
        <div class="content">
            <div class="notice"><strong>Please Note:</strong> This section will change the core text for things like 404 error banner and the message. It will also affect
            text for Author, Author blurbs and so on. Also <strong>note</strong> that changing some values may change another value related to it.</div>
            <div class="sideText">
                <h1>Default 404 err banner message</h1>
                <p>The following hook(s) will be changed: <strong>aisis_404_err_message_banner</strong>. 
                Which in turn changes the default text in the 404 error banner text.</p>
            </div>
            <?php do_settings_fields('aisis-core-options', 'aisis_default_404_banner_section');?><br />
            <div class="sideText">
                <h1>Default 404 err message</h1>
                <p>The following hook(s) will be changed: <strong>aisis_404_err_message</strong>. 
                Which in turn will change the default 404 error message that is displayed. 
                Yes you can use HTML here to style the header and the message.</p>
            </div>
            <?php do_settings_fields('aisis-core-options', 'aisis_default_404_message_section');?><br />
            <div class="sideText">
                <h1>Default Author Text & Blurb</h1>
                <p>The following hook(s) will be changed: <strong>aisis_author_default_text and aisis_loop_single_author_blurb_default</strong>. 
                Which in turn changes the authors default text for the author page and the default author blurb at the bottom of the post.
                To change them individually please edit your custom-functions.php file. </p>
            </div>
            <?php do_settings_fields('aisis-core-options', 'aisis_default_author_text_section');?><br />
            <div class="sideText">
                <h1>Default Category Text</h1>
                <p>The following hook(s) will be changed: <strong>aisis_category_default_text</strong>. 
                Which in turn changes the default category text for when viewing posts under a category.</p>
            </div>
            <?php do_settings_fields('aisis-core-options', 'aisis_default_category_text_section');?> <br />                   
            <div class="sideText">
                <h1>Default Footer Text</h1>
                <p>The following hook(s) will be changed: <strong>aisis_default_footer_text</strong>. 
                Which in turn changes the default footer text.</p>
            </div>
            <h2>Right Side of Footer - Text:</h2><br />
            <?php do_settings_fields('aisis-core-options', 'aisis_default_right_footer_text_section');?><br />
            <h2>Left Side of Footer - Text:</h2><br />
            <?php do_settings_fields('aisis-core-options', 'aisis_default_left_footer_text_section');?><br />
            <?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?>
        </div>
   </div>
   <div id="aisisSocial">
       <div class="content">
          <h1>Social Networks</h1>
          <p>Enter in your details bellow for the links that appear at the top of the navigation menu in the header.
          For each one of these that is filled out, you will see an icon.</p>
          <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?></p>
       </div>
      <div class="content">
            <div class="notice">For each section filled out here, you will see a coresponding icon above search on the front page
            displaying a link to that social network. You can also set up the hover deatils for that link as well, so that when users hover it,
            they see a custom message.</div>
            <div class="alignForm">
                <p>
                  <label><img src="<?php bloginfo('template_directory'); ?>/images/facebook.png" width="16" height="16"> Facebook Link:</label> 
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_facebook_link_section');?><br />
                  <label><img src="<?php bloginfo('template_directory'); ?>/images/facebook.png" width="16" height="16"> Facebook Hover:</label>
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_facebook_hover_section'); ?><br />
                  <label><img src="<?php bloginfo('template_directory');?>/images/twitter.png" width="16" height="16"> Twitter Link:</label> 
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_twitter_link_section');?><br />
                  <label><img src="<?php bloginfo('template_directory');?>/images/twitter.png" width="16" height="16"> Twitter Hover:</label>
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_twitter_hover_section'); ?><br />
                  <label><img src="<?php bloginfo('template_directory');?>/images/tumblr.png" width="16" height="16"> Tumblr Link:</label> 
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_tumblr_link_section');?><br />
                  <label><img src="<?php bloginfo('template_directory');?>/images/tumblr.png" width="16" height="16"> Tumblr Hover:</label>
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_tumblr_hover_section'); ?><br />
                  <label><img src="<?php bloginfo('template_directory');?>/images/google.png" width="16" height="16"> Google+:</label> 
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_google_link_section');?><br />
                  <label><img src="<?php bloginfo('template_directory');?>/images/google.png" width="16" height="16"> Google+ Hover:</label>
                  <br />
                  <?php do_settings_fields('aisis-core-options', 'aisis_google_hover_section'); ?><br />
                  <br />
                </p>
                <div class="bottomNotice">
                <h1>How Social Media Works</h1>
                <p>These coresponding links and custom message will display appropriate icons in the nav, when hovering over the user will see the custom test they entered.
                These are just links to various profiles and do not have any other functionality asssociated with them.</p>
                </div>
        	</div>
       </div>
   </div>
   <div id="aisisMisc">
       	<div class="content">
       		<h1>Misc. Options</h1>
       			<p>These options are all the options that didn't fit in else where
       			for the user to use. So we placed them here.</p>
       			<p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $core_options_save);?></p>
       		</div>
       	<div class="content">
            <div class="alignForm">
                <label>Show Related Posts?</label><br />
                <?php do_settings_fields('aisis-core-options', 'aisis_display_related_posts_section'); ?><br />
                <label>Should we Hide Categories and Tags?</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_display_categories_tags_section'); ?><br />
                <label>Upload your image!</label>
                <?php do_settings_fields('aisis-core-options', 'aisis_upload_header_image_section'); ?><br /> 
            </div>               
       	</div>
      </div>
   </div>
</div>
 <?php settings_fields( 'aisis-core-options' ); ?>
</form>
