<?php

	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		This is the Aisis Options page which allows you to set options
	 *		for the theme that are more basic then the editors where you can
	 *		edit various files.
	 *		
	 *		@author: Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 *
	 * =================================================================
	 */
	 
	 $aisis_form_element = new AisisForm();
	 
	 $basic_array_submit = array('value'=>'Save Your Work!', 'name'=>'defaults');
	 $facebook_save = array('value'=>'Link to Facebook!', 'name'=>'defaults');
	 $twitter_save = array('value'=>'Link to Twitter!', 'name'=>'defaults');
	 $tumblr_save = array('value'=>'Link to Tumblr!', 'name'=>'defaults');
	 $google_save = array('value'=>'Link to Google+!', 'name'=>'defaults');
	 $rss_save = array('value'=>'Link to RSS!', 'name'=>'defaults');

?>
<?php $aisis_forum_url = 'options.php?redirect_to=/wp-admin/admin.php?page=aisis-core-options' ?>
<form method="post" action="<?php echo $aisis_forum_url ?>">
<div id="coreTabs">
	<ul>
    	<li><a href="#aisis">Aisis Core Options</a></li>
        <li><a href="#aisisGit">Aisis General Options</a></li>
        <li><a href="#aisisAPI">Aisis Aditional</a></li>
    </ul>
    <div class="bottom"></div>
    <div id="aisis">
		<div class="box">
            <h1>Header Image's</h1>
            <p>Looking to chage the slider on the front of your blog? Uplaod your images here and watch the slider change!</p>
            <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?></p>
        </div>
        
        <div class="contents">
            <div class="notice">
                When you upload an image using this uploader your images will be stored in <strong>Aisis/images/imageheaders</strong> 
                It is recomdended you also upload thumb nail size images of your main images for responsiveness.
                Header Images ar <strong>1200x800</strong> and thumbs are <strong>100x75</strong>.
            </div>
            
            <div class="optionsSection">
                <div class="contents">
                <div class="greyBox">
                    <p>If you are looking to upload an image that can be used as the slider image then please do so here. 
                    The images in the <strong>images/headerimages</strong> will be used. as well as the thumbs there. 
                    Its is adbvised you upload thumbs as well to allow for responsiveness in the slider.</p>
                </div>
                <?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?>
                </div>
            </div>
        </div>
        
        <div class="box">
            <h1>Change Default Text</h1>
            <p>Looking to change some of the default text and options through out the theme?
            Edit the information bellow to change the default text through out the site.</p>
            <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?></p>
        </div>
        
        <div class="contents">
            <?php
            if(get_option('admin_404_banner_err_bool') == 'true' && get_option('admin_404_message_err_bool') == 'true' && get_option('admin_default_author_err_bool') == 'true' 
                && get_option('admin_default_cat_text_err_bool') == 'true' && get_option('admin_default_footer_text_err_bool') == 'true'){
                    ?>
                    <div class="success">We have successfully updated the site with new content that you have set bellow.</div>
                    <script>
                        $().toastmessage('showSuccessToast', "We have successfully updated the content on the site with the new content that you have set bellow.");
                    </script>
                    <?php
                    update_option('admin_404_banner_err_bool', '');
                    update_option('admin_404_message_err_bool', '');
                    update_option('admin_default_author_err_bool', '');
                    update_option('admin_default_cat_text_err_bool', '');
                    update_option('admin_default_footer_text_err_bool', '');
            }
            ?>
            <div class="notice">The following is a set of hooks that deisplay default content fopr things like authors and categories when the text for those have not been set. That is to say if an author does not set their bio then the <strong>aisis_author_default_text and aisis_loop_single_author_blurb_default</strong> will be used to display default text.</div>
            <div class="optionsSection">
                <?php settings_fields( 'aisis-core-options' ); ?>
                    <div class="greyBox">
                        <div class="title">Default 404 err banner message</div>
                        <p>The following hook(s) will be changed: <strong>aisis_404_err_message_banner</strong>. 
                        Which in turn changes the default text in the 404 error banner text.</p>
                    </div>
                   <?php do_settings_fields('aisis-core-options', 'aisis_default_404_banner_section');?><br />
                    <div class="greyBox">
                        <div class="title">Default 404 err message</div>
                        <p>The following hook(s) will be changed: <strong>aisis_404_err_message</strong>. 
                        Which in turn will change the default 404 error message that is displayed. 
                        Yes you can use HTML here to style the header and the message.</p>
                    </div>
                    <?php do_settings_fields('aisis-core-options', 'aisis_default_404_message_section');?><br />
                    <div class="greyBox">
                        <div class="title">Default Author Text & Blurb</div>
                        <p>The following hook(s) will be changed: <strong>aisis_author_default_text and aisis_loop_single_author_blurb_default</strong>. 
                        Which in turn changes the authors default text for the author page and the default author blurb at the bottom of the post.
                        To change them individually please edit your custom-functions.php file. </p>
                    </div>
                    <?php do_settings_fields('aisis-core-options', 'aisis_default_author_text_section');?><br />
                    <div class="greyBox">
                        <div class="title">Default Category Text</div>
                        <p>The following hook(s) will be changed: <strong>aisis_category_default_text</strong>. 
                        Which in turn changes the default category text for when vieing posts under a category.</p>
                    </div>
                    <?php do_settings_fields('aisis-core-options', 'aisis_default_category_text_section');?> <br />
                    <div class="greyBox">
                        <div class="title">Default Footer Text</div>
                        <p>The following hook(s) will be changed: <strong>aisis_default_footer_text</strong>. 
                        Which in turn changes the default footer text.</p>
                    </div>
                    <?php do_settings_fields('aisis-core-options', 'aisis_default_footer_text_section');?><br />
                    <?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?>
                
            </div>
        </div>
   </div>
   <div id="aisisGit">
       <div class="box">
          <h1>Social Networks</h1>
          <p>Enter in your details bellow for the links that appear at the top of the navigation menu in the header.
          For each one of these that is filled out, you will see an icon.</p>
          <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?></p>
       </div>
       <div class="contents">
            <div class="notice">For each section filled out here, you will see a coresponding icon above search on the front page
            displaying a link to that social network. You can also set up the hover deatils for that link as well, so that when users hover it,
            they see a custom message.</div>
            <div class="optionsSection">
                <div class="greyBox">
                    <div class="title">Facebook</div>
                    <p>Do you use FaceBook? Perhaps you have a page for your product or service! place your link to your page bellow and we will link to it!<br /><br />
                    Also take the time to fill out, if you wish, the hover over text so that when users hover over the icon they see your custom message.</p>
                </div>
                <label><img src="<?php bloginfo('template_directory'); ?>/images/facebook.png" width="16" height="16"> Facebook Link:</label> <br />
				<?php do_settings_fields('aisis-core-options', 'aisis_facebook_link_section');?><br />
                <label><img src="<?php bloginfo('template_directory'); ?>/images/facebook.png" width="16" height="16"> Facebook Hover:</label><br />
                 <?php do_settings_fields('aisis-core-options', 'aisis_facebook_hover_section'); ?><br />
                <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $facebook_save);?></p>
                <div class="greyBox">
                    <div class="title">Twitter</div>
                    <p>Obsessed with Twitter? Are you in love with everything Twitter is? Link to your profile here so that people can stalk you no matter where you are!<br /><br />
                    Also take the time to fill out, if you wish, the hover over text so that when users hover over the icon they see your custom message.</p>
                </div>
                <label><img src="<?php bloginfo('template_directory');?>/images/twitter.png" width="16" height="16"> Twitter Link:</label> <br />
				<?php do_settings_fields('aisis-core-options', 'aisis_twitter_link_section');?><br />
                <label><img src="<?php bloginfo('template_directory');?>/images/twitter.png" width="16" height="16"> Twitter Hover:</label><br />
                 <?php do_settings_fields('aisis-core-options', 'aisis_twitter_hover_section'); ?><br />
                <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $twitter_save);?></p>
                <div class="greyBox">
                    <div class="title">Tumblr</div>
                    <p>Do you have a Tumblr account? Want to show it off? Link to it bellow and let people follow you on Tumblr<br /><br />
                    Also take the time to fill out, if you wish, the hover over text so that when users hover over the icon they see your custom message.</p>
                </div>
                <label><img src="<?php bloginfo('template_directory');?>/images/tumblr.png" width="16" height="16"> Tumblr Link:</label> <br />
				<?php do_settings_fields('aisis-core-options', 'aisis_tumblr_link_section');?><br />
                <label><img src="<?php bloginfo('template_directory');?>/images/tumblr.png" width="16" height="16"> Tumblr Hover:</label><br />
                 <?php do_settings_fields('aisis-core-options', 'aisis_tumblr_hover_section'); ?><br />
                <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $tumblr_save);?></p>
                <div class="greyBox">
                    <div class="title">Goole+</div>
                    <p>Do you have a Google+ account? Do you want to share it with the world? Fill out the deatils bellow<br /><br />
                    Also take the time to fill out, if you wish, the hover over text so that when users hover over the icon they see your custom message.</p>
                </div>
                <label><img src="<?php bloginfo('template_directory');?>/images/google.png" width="16" height="16"> Google+:</label> <br />
				<?php do_settings_fields('aisis-core-options', 'aisis_google_link_section');?><br />
                <label><img src="<?php bloginfo('template_directory');?>/images/google.png" width="16" height="16"> Google+ Hover:</label><br />
                 <?php do_settings_fields('aisis-core-options', 'aisis_google_hover_section'); ?><br />
                <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $google_save);?></p>
                <div class="greyBox">
                    <div class="title">RSS</div>
                    <p>Do you have Feedburner? Do you have some other RSS Service? If so - Enter it in here.<br /><br />
                    Also take the time to fill out, if you wish, the hover over text so that when users hover over the icon they see your custom message.</p>
                </div>
                <label><img src="<?php bloginfo('template_directory');?>/images/feed.png" width="16" height="16"> Rss Link:</label> <br />
				<?php do_settings_fields('aisis-core-options', 'aisis_rss_link_section');?><br />
                <label><img src="<?php bloginfo('template_directory');?>/images/feed.png" width="16" height="16"> RSS Hover:</label><br />
                 <?php do_settings_fields('aisis-core-options', 'aisis_rss_hover_section'); ?><br />
                <p><?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $rss_save);?></p>
        	</div>
       </div>
   </div>
   <div id="aisisAPI">
   </div>
</div>
</form>
<script>
	$(function() {
		$( "#coreTabs" ).tabs();
	});
	
</script>