<div class="content">
	<?php
        $aisis_form = new AisisForm();
		$aisis_form->open_form(array(
			'method'=>'post',
			'action'=>'options.php?redirect_to=/wp-admin/admin.php?page=aisis-core-bbpress'
		));
	?>
    <div class="sideText">
        <h1>BBpress Core Options</h1>
        <p>The following options are core to BBPress. This means that these will affect your forums on a global level
        as opposed to a singular level.<p>
        <p><?php create_submit(); ?></p>
    </div>
    <div class="alignForm">
		<?php do_settings_fields('aisis-core-bbpress','aisis_bbpress_core_section'); ?>
    </div>
    <?php
	settings_fields('aisis-core-bbpress'); 
	$aisis_form->close_form();
	?>
</div>