<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This file is the CSS editor for Aisis in which it will
	 *		load in the custom/custom-functions.php file and allow you
	 *		to edit the file. If it is not there you will get an
	 *		error message telling you to create one.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 * =================================================================
	 */
	 
?>
        <div class="box">
        	<h1>PHP Editor</h1>
            <p>Looking to edit your custom-functions.php file? Make your changes bellow and hit the save button to see the changes take affect.</p>
        </div>
        
    	<div class="notice">This allows you to edit your <strong>custom-css.css</strong> file and change the way the site looks.</div>
		<?php $aisis_forum_url = 'options.php?redirect_to=/wp-admin/admin.php?page=aisis-css-editor' ?>
        <form method="post" action="<?php echo $aisis_forum_url ?>">
          	<?php settings_fields( 'aisis-css-editor' ); ?>
        	<?php do_settings_fields('aisis-css-editor', 'aisis_css_editor_section'); ?>
            <input type="submit" id="published" name="published" value="Save CSS"/>
        </form>