<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This file is the Js editor for Aisis in which it will
	 *		load in the custom/custom-js.js file and allow you
	 *		to edit the file. If it is not there you will get an
	 *		error message telling you to create one.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 * =================================================================
	 */
	 
?>
        <div class="box">
        	<h1>JavaScript Editor</h1>
            <p>Looking to add your own custom JS? add it bellow and hit save and watch your java script functions come alive!</p>
        </div>
        
    	<div class="notice">This allows you to edit your <strong>custom-js.js</strong> file and add functionality to the site via JavaScript.</div>
		<?php $aisis_forum_url = 'options.php?redirect_to=/wp-admin/admin.php?page=aisis-js-editor' ?>
        <form method="post" action="<?php echo $aisis_forum_url ?>">
        	<?php settings_fields( 'aisis-js-editor' ); ?>
            <?php do_settings_fields('aisis-js-editor', 'aisis_js_editor_section'); ?>
            <input type="submit" id="published" name="published" />
        </form>
    