<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This file is the Js editor for Aisis in which it will
	 *		load in the custom/custom-js.js file and allow you
	 *		to edit the file. If it is not there you will get an
	 *		error message telling you to create one.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 * =================================================================
	 */
	 
	 $aisis_form_element = new AisisForm();
	 $basic_array_submit = array('value'=>'Save Your Work!', 'name'=>'defaults', 'class'=>'phpEditorButton');
	 
?>
        <div class="content">
        	<h1>PHP Editor</h1>
            <p>Looking to add some functions? Add them here and we will write them to your custom-function.php file. </p>
        </div>
        <div class="content">
        	<?php if(is_multisite()){ ?>
            <div class="notice"><strong>ATTN!</strong> Please make sure to back up this file: <strong><?php echo CUSTOM . 'custom-functions.php'; ?></strong>.
            also note you <strong>MUST</strong> start this file off with opening and closing php tags.</div>
            <?php }else{ ?>
            <div class="notice"><strong>Note!</strong> Back this file up and be careful as you may cause your self a white screen of death.</div>
            <?php }
			
			$aisis_forum_url = 'options.php?redirect_to=/wp-admin/admin.php?page=aisis-php-editor' ?>
            <form method="post" action="<?php echo $aisis_forum_url ?>">
                <?php settings_fields( 'aisis-php-editor' ); ?>
                <?php do_settings_fields('aisis-php-editor', 'aisis_php_editor_section'); ?>
                <?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?>
            </form>
            <br />
        </div>
    