<?php
	/**
	 *
	 * ==================== [-DO NOT TOUCH!!!-] =======================
	 *
	 *		This file is the Js editor for Aisis in which it will
	 *		load in the custom/custom-js.js file and allow you
	 *		to edit the file. If it is not there you will get an
	 *		error message telling you to create one.
	 *		
	 *		@author:  Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->Modules
	 * =================================================================
	 */
	 
	 $aisis_form_element = new AisisForm();
	 $basic_array_submit = array('value'=>'Save Your Work!', 'name'=>'defaults', 'class'=>'phpEditorButton');
	 
?>
        <div class="box">
        	<div class="title">JavaScript Editor</div>
            <p>Looking to add your own custom JS? add it bellow and hit save and watch your java script functions come alive!</p>
        </div>
        <div class="contents">
            <div class="notice">This allows you to edit your <strong>custom-js.js</strong> file and add functionality to the site via JavaScript.</div>
            <?php $aisis_forum_url = 'options.php?redirect_to=/wp-admin/admin.php?page=aisis-php-editor' ?>
            <form method="post" action="<?php echo $aisis_forum_url ?>">
                <?php settings_fields( 'aisis-php-editor' ); ?>
                <?php do_settings_fields('aisis-php-editor', 'aisis_php_editor_section'); ?>
                <?php $aisis_form_element->creat_aisis_form_element('input', 'submit', $basic_array_submit);?>
            </form>
        </div>
    