<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		We use this new kind of template a -Meta-Template to style
	 *		and create the articles and essays meta box for the ae 
	 *		post type.
	 *
	 *		The Css used here is located in the admin panel css
	 *		under the AdminPanel->Options->Required->AdminPanelCSS.css
	 *
	 *		@see AisisCore->AisisView-> Class-Aisis-Form
	 *		
	 *		@author: Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->AisisCustomPostTypes->MetaTemplates
	 *
	 * =================================================================
	 */
	 
	global $post;
	$values = get_post_custom( $post->ID );
	
	$aisis_create_form_elements = new AisisForm();
?>

    <div class="aisis_meta_control">
        
          <div class="notice"><strong>Note:</strong> This is an optional setting that allows you to set the refrences, up to six, of your essay or article. 
          Refrences to where you obtained your data and so on.</div>
          <br  />
          <p>
              <label for="aisis_meta_box_link_one">Enter a url for a refrence</label>                        
			  <?php
              if(isset($values['aisis_meta_box_link_one']) && !empty($values['aisis_meta_box_link_one'])){
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_one',
						'id' => 'aisis_meta_box_link_one',
						'value' => $values['aisis_meta_box_link_one'][0]
				  );
			  }else{
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_one',
						'id' => 'aisis_meta_box_link_one',
						'value' => ''
				  );				  
			  }
			  $aisis_create_form_elements->creat_aisis_form_element('input', 'url', $array_of_attributes);
              ?>
          </p>  
          <p>
              <label for="aisis_meta_box_link_one_desc">Enter a description</label>
			  <?php
              if(isset($values['aisis_meta_box_link_one_desc']) && !empty($values['aisis_meta_box_link_one_desc'])){
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_one_desc',
						'id' => 'aisis_meta_box_link_one_desc',
						'value' => $values['aisis_meta_box_link_one_desc'][0]
				  );
			  }else{
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_one_desc',
						'id' => 'aisis_meta_box_link_one_desc',
						'value' => ''
				  );				  
			  }
			  $aisis_create_form_elements->creat_aisis_form_element('textarea', '', $array_of_attributes);
              ?>
          </p>  
          <p>
              <label for="aisis_meta_box_link_two">Enter a url for a refrence</label>
			  <?php
              if(isset($values['aisis_meta_box_link_two']) && !empty($values['aisis_meta_box_link_two'])){
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_two',
						'id' => 'aisis_meta_box_link_two',
						'value' => $values['aisis_meta_box_link_two'][0]
				  );
			  }else{
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_two',
						'id' => 'aisis_meta_box_link_two',
						'value' => ''
				  );				  
			  }
			  $aisis_create_form_elements->creat_aisis_form_element('input', 'url', $array_of_attributes);
              ?>              
          </p>  
          <p>
              <label for="aisis_meta_box_link_two_desc">Enter a description</label>
			  <?php
              if(isset($values['aisis_meta_box_link_two_desc']) && !empty($values['aisis_meta_box_link_two_desc'])){
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_two_desc',
						'id' => 'aisis_meta_box_link_two_desc',
						'value' => $values['aisis_meta_box_link_two_desc'][0]
				  );
			  }else{
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_two_desc',
						'id' => 'aisis_meta_box_link_two_desc',
						'value' => ''
				  );				  
			  }
			  $aisis_create_form_elements->creat_aisis_form_element('textarea', '', $array_of_attributes);
              ?>               
          </p>                                        
          <p>
              <label for="aisis_meta_box_link_three">Enter a url for a refrence</label>
			  <?php
              if(isset($values['aisis_meta_box_link_three']) && !empty($values['aisis_meta_box_link_three'])){
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_three',
						'id' => 'aisis_meta_box_link_three',
						'value' => $values['aisis_meta_box_link_three'][0]
				  );
			  }else{
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_three',
						'id' => 'aisis_meta_box_link_three',
						'value' => ''
				  );				  
			  }
			  $aisis_create_form_elements->creat_aisis_form_element('input', 'url', $array_of_attributes);
              ?>               
          </p>  
          <p>
              <label for="aisis_meta_box_link_three_desc">Enter a description</label>
			  <?php
              if(isset($values['aisis_meta_box_link_three_desc']) && !empty($values['aisis_meta_box_link_three_desc'])){
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_three_desc',
						'id' => 'aisis_meta_box_link_three_desc',
						'value' => $values['aisis_meta_box_link_three_desc'][0]
				  );
			  }else{
				  $array_of_attributes = array(
						'name' => 'aisis_meta_box_link_three_desc',
						'id' => 'aisis_meta_box_link_three_desc',
						'value' => ''
				  );				  
			  }
			  $aisis_create_form_elements->creat_aisis_form_element('textarea', '', $array_of_attributes);
              ?>               
          </p>   
                 
    </div>