<?php
	/**
	 *
	 * ==================== [DONT TOUCH THIS FILE!] ====================
	 *
	 *		We use this new kind of template a -Meta-Template to style
	 *		and create the articles and essays meta box for the ae 
	 *		post type.
	 *
	 *		The Css used here is located in the admin panel css
	 *		under the AdminPanel->Options->Required->AdminPanelCSS.css
	 *
	 *		@see AisisCore->AisisView-> Class-Aisis-Form
	 *		
	 *		@author: Adam Balan
	 *		@version: 1.0
	 *		@package: AisisCore->AdminPanel->AisisCustomPostTypes->MetaTemplates
	 *
	 * =================================================================
	 */
	 
	  global $post;
	  $values = get_post_custom( $post->ID );
	  
	  $aisis_create_form_elements = new AisisForm();
?>

      <div class="aisis_meta_control">
          
            <div class="metaNotice"><strong>Note:</strong> This section allows for HTML Elements like links to be passed in. We will show this optional content in a black box at the bottom
            of the slider for this content. 
            <p>You can use things like: div id of <strong>sliderText</strong>, <strong>sliderImage</strong> and a class of <strong>sliderReadMore</strong> to align images to the left, float text to the right and give the read more button some class.</p></div>
            <br  /> 
            <p>
                <?php
				$aisis_create_form_elements->create_aisis_form_element('label', array('for'=>'aisis_slider_meta_box_desc',
				'value'=>'Enter your content here for the slider'));
                if(isset($values['aisis_slider_meta_box_desc']) && !empty($values['aisis_slider_meta_box_desc'])){
					$aisis_create_form_elements->create_aisis_form_element('textarea', array(
                          'name' => 'aisis_slider_meta_box_desc',
                          'id' => 'aisis_slider_meta_box_desc',
                          'value' => $values['aisis_slider_meta_box_desc'][0]
					));
                }else{
					$aisis_create_form_elements->create_aisis_form_element('textarea', array(
                          'name' => 'aisis_slider_meta_box_desc',
                          'id' => 'aisis_slider_meta_box_desc',
                          'value' => ''
					));				  
                }
                ?>                
            </p>  
            <p>
                <?php
				$aisis_create_form_elements->create_aisis_form_element('label', array('for'=>'aisis_slider_meta_box_short_desc'
				, 'value'=>'Enter a short description for the "black title bar" at the bottom of the slider.'));
                if(isset($values['aisis_slider_meta_box_short_desc']) && !empty($values['aisis_slider_meta_box_short_desc'])){
					$aisis_create_form_elements->create_aisis_form_elements('textarea', array(
					      'name' => 'aisis_slider_meta_box_short_desc',
                          'id' => 'aisis_slider_meta_box_short_desc',
                          'value' => $values['aisis_slider_meta_box_short_desc'][0]
					));
                }else{
					$aisis_create_form_elements->create_aisis_form_element('textarea', array(
					      'name' => 'aisis_slider_meta_box_short_desc',
                          'id' => 'aisis_slider_meta_box_short_desc',
                          'value' => ''
					));			  
                }
                ?>
            </p>
            
      </div>