<div class="sideText">
    <h1>Custom Text Options</h1>
    <p>Bellow you can set the various different types of custom text. From default author text, 
    if an author has not entered in a short bio to 404 messages for when the user searches for 
    something tht does not exist. We support only:
    <strong>P tags, Blockquote tags, a tags, H1,2 and 3 tags.</strong></p>
    <div class="notice"><strong>Note:</strong> We use the wordpresss hooks 
    system to display default content and display the content
    you create here. Please keep that in mind when overriding the 
    <a href="http://aisis.adambalan.com/documentation/aisis-hooks/">Aisis Hooks</a>.</div>
    <p><?php create_submit(); ?></p>
</div>
<div class="alignForm">
	<?php do_settings_fields('aisis-core-options','aisis_custom_text_section'); ?>
</div>