<?php 
	$menu_options = array(
		'container' => '',
		'menu_class' => 'nav nav-pills',
       	'fallback_cb' => '',
		'theme_location'  => 'footer_links',
	);
?>

<div id="footer">
	<div class="container containerTop">
		<div class="row">
			<div class="span6">
				<p class="muted credit">
					Test Footer content with an <a href="http://google.ca">Example Link</a>.
				</p>
			</div>
			<div class="span3">
				<?php wp_nav_menu($menu_options); ?>
			</div>
		</div>
	</div>
</div>
