<?php 
	$menu_options = array(
		'menu' => 'main-menu',
        'menu_class' => 'nav',
       	'fallback_cb' => '',
        'menu_id' => 'main-menu',
        'walker' => new CoreTheme_NavWalker()
	);
?>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="<?php echo home_url('/'); ?>" class="brand"><?php bloginfo('name'); ?></a>
      <div class="nav-collapse">
      	<?php wp_nav_menu($menu_options); ?>
        <form class="navbar-search pull-right" action="">
          <input type="text" class="search-query span2" placeholder="Search">
        </form>
      </div>
    </div>
  </div>
</div>