<?php

$posts = new CoreTheme_AdminPanel_Form_Posts();
$custom = new CoreTheme_AdminPanel_Form_CustomPost();

$array = array(
	'method' => 'post',
	'action' => 'options.php',
	'class' => 'form-vertical',
	'settings' => 'aisis_options',
	array(
		'tab' => 'Posts',
		'elements' => array(
			$posts->elements()
		),
	),
	array(
		'tab' => 'Custom Posts',
		'elements' => array(
			$custom->elements()
		),
	),	
	array(
		'tab' => 'content version 2',
		'elements' => 'content for this tab as well',
	)
);

$tabbed_form = new CoreTheme_Form_TabbedForm($array);
?>

<div class="container">
	<div class="jumbotron subhead">
		<h1>Aisis - <small>Version 1.2</small></h1>
		<p class="lead">A revolution in WordPress theme design!!</p>
		<p class="lead">
			<?php
			if(isset($_POST['aisis_reset'])){
				$theme = AisisCore_Factory_Pattern::create('AisisCore_Template_Builder');
				$theme->reset_theme_options();
				$options = get_option('aisis_reset');
				if($options == 'true'){
					echo '<div class="alert alert-success"><strong>SUCCESS!!!!</strong> All Options have been reset! You can start again!</div>';
					update_option('aisis_reset', 'false');
				}
			}
			
			$form = new CoreTheme_AdminPanel_Form_Reset(
				array(
					'action' => '',
					'method' => 'post',
					'class' => 'form-horizontal'
				)
			);
			
			echo $form;
			?>
		</p>
	</div>	
	<?php 
	
	$option = get_option('aisis_success');
	if($option == 'true'){
		echo '<div class="alert alert-success"><strong>SUCCESS!!!!</strong> You have made some killer changes to Aisis! <a href="'.site_url().'">Check it out now!</a></div>';
		update_option('aisis_success', 'false');
	}
	
	echo $tabbed_form; 
	
	?>
</div>

<script>
$(document).ready(function(){     
	$('.posts').click(function(){
		if ($(this).attr("id") == "list"){
	   		$('.sectionLists').show();
	    } else {
	    	$('.sectionLists').hide();
	    }
	});
	
	$('.posts').click(function(){
		if ($(this).attr("id") == "row"){
	   		$('.sectionRows').show();
	    } else {
	    	$('.sectionRows').hide();
	    }
	});	
	
	$('.posts').click(function(){
		if ($(this).attr("id") == "row"){
	   		$('.sectionRows').show();
	    } else {
	    	$('.sectionRows').hide();
	    }
	});	
	
	$('.category_header').click(function(){
		if ($(this).attr("id") == "category"){
	   		$('.sectionCategory').show();
	    } else {
	    	$('.sectionCategory').hide();
	    }
	});	
	
	$('.author_posts').click(function(){
		if ($(this).attr("id") == "author"){
	   		$('.sectionAuthor').show();
	    } else {
	    	$('.sectionAuthor').hide();
	    }
	});
	
	$('.tag_header').click(function(){
		if ($(this).attr("id") == "tag"){
	   		$('.sectionTag').show();
	    } else {
	    	$('.sectionTag').hide();
	    }
	});
	
	$('.carouselGlobal').click(function(){
		if ($(this).attr("id") == "carousel"){
	   		$('.sectionCarousel').show();
	    } else {
	    	$('.sectionCarousel').hide();
	    }
	});						
	
	if ($('input[value=lists]:radio:checked').attr('id') === "list") {
        $('.sectionLists').show();
    }

	if ($('input[value=rows]:radio:checked').attr('id') === "row") {
        $('.sectionRows').show();
    }	
    
    if ($('input[value=category_header]:checkbox:checked').attr('id') === "category") {
        $('.sectionCategory').show();
    }
     
    if ($('input[value=author_posts]:checkbox:checked').attr('id') === "author") {
        $('.sectionAuthor').show();
    } 
    
    if ($('input[value=tag_header]:checkbox:checked').attr('id') === "tag") {
        $('.sectionTag').show();
    } 
    
    if ($('input[value=carousel_global]:checkbox:checked').attr('id') === "carousel") {
        $('.sectionCarousel').show();
    }  
    
	$("#jumbotron").change(function() {
	    if (this.checked) {
	        $("#socialbar").prop("disabled", false);
	    }
	    else {
	        $("#socialbar").prop("disabled", true);
	    }
	});             
    
    $("#displayLists").popover();
	$("#morePostsList").popover();
	$("#displayRows").popover();
	$("#displayMoreRows").popover();
	$("#regularPosts").popover();
	$("#categoryHeader").popover();
	$("#categoryDescription").popover();
	$("#categorySidebar").popover();
	$("#categoryTags").popover();
    $("#authorPosts").popover();
	$("#authorImage").popover();
	$("#authorBio").popover();
	$("#authorSidebar").popover();
	$("#tagHeader").popover();
	$("#tagDescription").popover();
	$("#tagSidebar").popover();
    $("#carouselGlobal").popover();
	$("#carouselHome").popover();
	$("#carouselSingle").popover();
	$("#jumbotronPop").popover();
	$("#socialbarPop").popover();
	$("#miniFeedGlobal").popover();
	$("#miniFeedHome").popover();
	$("#miniFeedSingle").popover();
	
	enableCarousel();
	$('#carousel').click(enableCarousel);
	enableMini();
	$('#miniFeedGlobal').click(enableMini);		
});

	function enableCarousel(){
		if(this.checked){
			$('input.carousel').attr("disabled", true);
		}
	}
	
	function enableMini(){
		if(this.checked){
			$('input.mini').attr("disabled", true);
		}
	}	
</script>