<?php

function url_element(){
	$url = array(
		'name' => 'aisis_options[index_more_posts]',
		'placeholder' => 'Url'	
	);

	$url_element = new CoreTheme_Form_Elements_Url($url);
	$url_element->set_label('Url of the content', 'control-label');

	return $url_element;
}

function submit_element(){
	$submit = array(
		'value'=> 'Submit',
	);

	$submit_element = new CoreTheme_Form_Elements_Submit($submit);
	return $submit_element;
}

$array = array(
	'method' => 'post',
	'action' => 'options.php',
	'settings' => 'aisis_options',
	array(
		'tab' => 'content',
		'elements' => array(
			url_element(),
			submit_element()
		),
	),
	array(
		'tab' => 'content version 2',
		'elements' => 'content for this tab as well',
	)
);

$tabbed_form = new CoreTheme_Form_Helpers_TabbedForm($array);
echo $tabbed_form;

var_dump(get_option('aisis_options'));
