<?php 
$file = new CoreTheme_FileHandling_FileHandling();
if((count($file->search_for_themes()) == 0) && (count($file->search_for_packages())== 0)){
	echo '<div class="alert alert-notice">You do not have any themes or packages uploaded.
		please consider uploading some.</div>';
}else{
	echo '<div class="alert alert-info">Select from below themes and packages and watch your site change!</div>';
	
	$theme = new CoreTheme_AdminPanel_Template_Form_SelectTheme();
	$package = new CoreTheme_AdminPanel_Template_Form_SelectPackages();

	$array = array(
		'method' => 'post',
		'action' => 'options.php',
		'class' => 'form-vertical',
		'settings' => 'aisis_options',
		array(
			'tab' => 'Themes',
			'elements' => array(
				$theme->elements()
			),
		),
		array(
			'tab' => 'Packages',
			'elements' => array(
				$package->elements()
			),
		),	
	);

	$tabbed_form = new CoreTheme_Form_TabbedForm($array);
	echo $tabbed_form;
} 

$url = ($_SERVER['HTTPS'] ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . '/'; 

?>
<script>
(function($){	
    $(document).ready(function(){
        $('.unslectPackages').click(function(e){
          var el = $(this).prev('input[type="checkbox"]');
          if(el.is(':checked')){
               el.prop('checked',false); 
               $.ajax({
                  url  : '<?php echo $url . 'wp-admin/admin-ajax.php' ?>',
                  type : 'POST',
                  data : { 
                      action : 'uncheck_package',
                      element_value : el.val()
                  },      
                  success: function(result){
                    console.log(result);
                  },
                  error: function(jqXHR, textStatus, errorThrown ){
                    console.log(jqXHR, textStatus, errorThrown);
                  } 
              });
          }
           e.preventDefault();
        });
        $('.unslectThemes').click(function(e){
          var el = $(this).prev('input[type="radio"]');
          if(el.is(':checked')){
               el.prop('checked',false); 
               $.ajax({
                  url  : '<?php echo $url . 'wp-admin/admin-ajax.php' ?>',
                  type : 'POST',
                  data : { 
                      action : 'uncheck_themes',
                      element_value : el.val()
                  },      
                  success: function(result){
                    console.log(result);
                  },
                  error: function(jqXHR, textStatus, errorThrown ){
                    console.log(jqXHR, textStatus, errorThrown);
                  } 
              });
          }
           e.preventDefault();
        });        
    }); 
 })(jQuery);
 </script>
