<?php 
$update = new CoreTheme_Update();
$aisis_template = AisisCore_Factory_Pattern::create('AisisCore_Template_Builder');
if($update->check_for_update()){
    ?>
    <div class="modified-hero-unit">
         <a href="<?php echo $update->grab_link() ?>" 
           class="btn btn-success pull-right marginTop14 marginright210">Read the latest update notes!</a>
        <h2>Aisis Theme <?php echo $update->check_theme_version(); ?> Has Arrived!</h2>
        <?php if($update->check_download() != 'yes'){ ?>
            <p>
                We have an update for you! <?php echo $update->check_theme_version(); ?> 
                packs a whole new punch with all kinds of new goodies and 
                features and fixes! We are so excited!
            </p>
        <?php }else{ ?>
            <p>
                Good news! We have a new update for you! Aisis <?php echo $update->check_theme_version() ?>
                comes with new features, fixes and improvements! How ever, you will have to download this
                version instead of on-click-installing it. We provided the download link for you.
            </p>
        <?php } ?>
        <div class="alert">
            <strong>Note:</strong> 
            We suggest that you put your site into maintenance mode.
            We can also help you with the update, see this 
            <a href="http://aisis.adambalan.com/tutorials/how-to-update-aisis/">
                tutorial on how to.
            </a>
        </div>
        <?php $aisis_template->render_partial('downloadUpdate'); ?>
    </div>
    <?php
}else{
    echo '<div class="alert alert-success">
            <strong>Everything is Uptodate!</strong> 
                You have the latest version of Aisis :D 
          </div>';
}
?>
