<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/lib/Javascript/plugins/jquery.snipit.js' ?>"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/AisisCore/ShortCodes/lib/ShortCode-JS.js' ?>"></script>
<link href="<?php echo get_template_directory_uri() . '/lib/Javascript/plugins/pluginCss/snipit.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo get_template_directory_uri() . '/AisisCore/AdminPanel/assets/jquery-ui-1.8.19.custom.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo get_template_directory_uri() . '/AisisCore/ShortCodes/lib/Shortcode-Css.css' ?>" rel="stylesheet" type="text/css">
<script type="text/javascript">

jQuery(document).ready(function($){

	// wrap image with <span class="image-wrap"> for styling
	$('.imgPost img').each(function() {
		var imgClass = $(this).attr('class');
		$(this).wrap('<span class="image-wrap ' + imgClass + '" style="width: auto; height: auto;"/>');
		$(this).removeAttr('class');
	});

	//because JS syntax highlighting looks better
	$("pre.js").snippet("javascript",{style:"acid", showNum:false});
	$("pre.styles").snippet("css",{style:"acid"});
	$( "#tabs" ).tabs();

});


</script>

<div id="tabs">
  <ul>
    <li><a href="#aisis">Introduction</a></li>
    <li><a href="#postImages">Genral Codes</a></li>
    <li><a href="#postCode">Implementing Code</a></li>
  </ul>
  <div id="aisis">
    <div class="contentSection">
      <div class="title"> Aisis Short Codes </div>
      <div class="section">
        <p>Aisis short codes are Aisis Specific short codes that help you, the user, get things done faster, easier and more efficient than ever before. 
          
          We give you examples of what the short code will do, an easy insert into post button and of course what the short code will look like once in your editor.</p>
        <p>Aisis Short codes are simply the best thing ever when writing a WordPress post, custom or not, pages and 
          
          anything else where you might want to integrate short codes.</p>
      </div>
      <div class="middleText"> Example: </div>
      <pre class="js">

            [glossyimg] img src [/glossyimg]

            </pre>
      <div class="imgPost centerImage">
        <figure class="post-image glossy"> <img src="<?php bloginfo('template_directory');?>/images/natureForest.jpg" width="300" height="300"/> </figure>
      </div>
    </div>
  </div>
  <div id="postImages">
    <div class="contentSection">
      <div class="title"> General Short Codes </div>
      <div class="section">
        <p> These general short codes allow you to insert content into posts, pages, articles and more with a simple click of  button. </p>
      </div>
      <div class="middleText"> Glossy Image </div>
      <div class="section">
          <p>
          The following short code will give your images a glossy look that can really make the image pop.<br /><br />
          <strong>Note:</strong> If your browser does not support CSS3 we will do a fall back to a regular image.
          </p>
      </div>
      <pre class="js">[glossyimg] img src [/glossyimg]</pre>
      
      <div class="imgPost centerImage">
        <figure class="post-image glossy"> <img src="<?php bloginfo('template_directory');?>/images/natureForest.jpg" width="300" height="300"/> </figure>
      </div>
      <input type="button" value="Insert Into Post!" onclick="glossyImage()" />

      <div class="middleText"> Soft Image </div>
      <div class="section">
          <p>
          The following short code will give your images a soft look that can really bring emotion to an image.<br /><br />
          <strong>Note:</strong> If your browser does not support CSS3 we will do a fall back to a regular image.
          </p>
      </div>
      <pre class="js">[softimg] img src [/softimg]</pre>
      <div class="imgPost centerImage">
        <figure class="post-image soft-embossed"> <img src="<?php bloginfo('template_directory');?>/images/natureForest.jpg" width="300" height="300"/> </figure>
      </div>
      <input type="button" value="Insert Into Post!" onclick="softImage()" />

      <div class="middleText"> Info Post </div>
      <div class="section">
          <p>
          Wan't to quickly sum up an article or a paragraph? Well now you can! Really dfrive home the point
          of your posts with the info tag.
          </p>
      </div>
      <div class="infoPost"> This is some info or a summary about said article or paragraph </div>
      <input type="button" value="Insert Into Post!" onclick="info()" />
      
      <div class="middleText"> Update Post </div>
      <div class="section">
          <p>
          Made an update to your content? use this tag to really catch the reader attention!
          </p>
      </div>      
      <div class="updatePost"> This is some info or a summary about said article or paragraph </div>
      <input type="button" value="Insert Into Post!" onclick="update()" />

      <div class="middleText"> Create a Blue Button </div>
      <div class="blueButton"><a href="#" class="text">Blue Button</a></div>
      <input type="button" value="Insert Into Post!" onclick="aisisBlueButton()" />

	  <div class="middleText"> Create a Red Button </div>
      <div class="redButton"><a href="#" class="text">Red Button</a></div>
      <input type="button" value="Insert Into Post!" onclick="aisisRedButton()" />

      <div class="middleText"> Create a green Button </div>
      <div class="greenButton"><a href="#" class="text">Green Button</a></div>
      <input type="button" value="Insert Into Post!" onclick="aisisGreeneButton()" />    
    </div>
  </div>
  <div id="postCode">
    <div class="contentSection">
      <div class="title"> Implementing Code </div>
      <div class="section">
        <p>Ever find your self needing to insert code into a post or page? Well we provide tools to do just that!</p>
      </div>
      <div class="middleText"> JavaScript </div>
      <pre class="js">function(){}</pre>
      <input type="button" value="Insert Into Post!" onclick="jsCode()" />
      <br />
      <div class="middleText"> CSS </div>
      <pre class="styles">.css{}</pre>
      <input type="button" value="Insert Into Post!" onclick="cssCode()" />
      <br />
    </div>
  </div>
</div>
