<style type="text/css">

/** Image Based Jazz **/
.image-wrap {
	position : relative;
	display : inline-block;
	max-width : 100%;
	vertical-align : bottom;
}
.image-wrap:after {
	content : ' ';
	width : 100%;
	height : 100%;
	position : absolute;
	top : -1px;
	left : -1px;
	border : 1px solid #1b1b1b;
	border-radius : 7px;
}
.image-wrap img {
	vertical-align : bottom;
	border-radius : 6px;
}
.soft-embossed .image-wrap:after {
	-webkit-box-shadow: inset 0 0 3px rgba(0,0,0,1), inset 0 1px 1px rgba(255,255,255,.5), inset 0 -6px 2px rgba(0,0,0,.6), inset 0 -8px 2px rgba(255,255,255,.3);
	-moz-box-shadow: inset 0 0 3px rgba(0,0,0,1), inset 0 1px 1px rgba(255,255,255,.5), inset 0 -6px 2px rgba(0,0,0,.6), inset 0 -8px 2px rgba(255,255,255,.3);
	box-shadow: inset 0 0 3px rgba(0,0,0,1), inset 0 1px 1px rgba(255,255,255,.5), inset 0 -6px 2px rgba(0,0,0,.6), inset 0 -8px 2px rgba(255,255,255,.3);
}
.glossy .image-wrap:before {
	position: absolute;
	content: ' ';
	width: 100%;
	height: 50%;
	top: 0;
	left: 0;
	-webkit-border-top-left-radius: 7px;
	-webkit-border-top-right-radius: 7px;
	-moz-border-radius-topleft: 7px;
	-moz-border-radius-topright: 7px;
	border-top-left-radius: 7px;
	border-top-right-radius: 7px;
	background: -moz-linear-gradient(top, rgba(255,255,255,0.6) 0%, rgba(255,255,255,.15) 100%);
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, rgba(255,255,255,0.6)), color-stop(100%, rgba(255,255,255,.15)));
	background: linear-gradient(top, rgba(255,255,255,0.6) 0%, rgba(255,255,255,.15) 100%);
}
.center-image{
	margin: 20px auto 20px auto;
	width: 350px;
	height: 350px;
}

input[type="button"]{
	background-color:rgb(233,239,222);
	width:112px;
	height:39px;
	border-color:rgb(204,204,204);
	border-width:1px;
	border-radius:4px;
	border-style:solid;
	text-align:center;
	color:#15568A;
	cursor:pointer;
}

/** Post Specific **/
.infoPost{
	width : 75%;
	margin-left : -20px;
	margin-bottom : 10px;
	border-left : 5px solid #796d2d;
	background : #e0dcbe;
	padding : 10px 10px 10px 35px;
	font-size : 14px;
}
.updatePost{
	width : 75%;
	margin-left : -20px;
	margin-bottom : 10px;
	border-left : 5px solid #293947;
	background : #c1cadb;
	padding : 10px 10px 10px 35px;
	font-size : 14px;
}

/** Over All Layout **/
.contentSection{
	background-color:rgb(255,255,255);
	width:98%;
	margin-left: -15px;
	padding: 20px;
	border-color:rgb(204,204,204);
	border-width:1px;
	border-radius:6px;
	border-style:solid;
	box-shadow:2px 4px 4px rgba(221,221,221,0.65);
}
.section{
	background-color:rgb(213,221,227);
	width:90%;
	margin: 10px auto 10px auto;
	padding: 20px;
	border-color:rgb(204,204,204);
	border-width:1px;
	border-radius:4px;
	border-style:solid;
}
.title{
	text-align:center;
	font-size:24px;
}
.middleText{
	text-align:center;
	font-size:18px;	
}
.centerImage{
	margin-left: 116px;
}
/** Jquery UI Changes **/
.ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header .ui-state-default {
	background-color: #F5FAFA !important;
	border-color: #E7EEF0 !important;
	-moz-border-top-right-radius: 4px !important;
	-moz-border-top-left-radius: 4px !important;
	-webkit-border-top-right-radius: 4px !important;
	-webkit-border-top-left-radius: 4px !important;
	border-top-right-radius: 4px !important;
	border-top-left-radius: 4px !important;
}

.ui-state-active, .ui-widget-content .ui-state-active, .ui-widget-header .ui-state-active {
	background-color: #D7E5E9 !important;
	border-color: #C7DBDF !important;
	-moz-border-top-right-radius: 4px !important;
	-moz-border-top-left-radius: 4px !important;
	-webkit-border-top-right-radius: 4px !important;
	-webkit-border-top-left-radius: 4px !important;
	border-top-right-radius: 4px !important;
	border-top-left-radius: 4px !important;
	height: 37px !important;
}

.ui-widget-content {
	border: none !important;
	background: #fff !important;
}

</style>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo get_template_directory_uri() . '/lib/Javascript/plugins/jquery.snipit.js' ?>"></script>

<link href="<?php echo get_template_directory_uri() . '/lib/Javascript/plugins/pluginCss/snipit.css' ?>" rel="stylesheet" type="text/css">
<link href="<?php echo get_template_directory_uri() . '/AisisCore/AdminPanel/Modules/Required/jquery-ui-1.8.19.custom.css' ?>" rel="stylesheet" type="text/css">

<script type="text/javascript">
jQuery(document).ready(function($){
	// wrap image with <span class="image-wrap"> for styling
	$('.imgPost img').each(function() {
		var imgClass = $(this).attr('class');
		$(this).wrap('<span class="image-wrap ' + imgClass + '" style="width: auto; height: auto;"/>');
		$(this).removeAttr('class');
	});
	
	//because JS syntax highlighting looks better
	$("pre.js").snippet("javascript",{style:"acid", showNum:false})
	$("pre.styles").snippet("css",{style:"acid"})
	$( "#tabs" ).tabs();
});

function softImage () {
	var debug = true;
	try{
		var win = window.dialogArguments || opener || parent || top;
		win.send_to_editor('[softimg]Place Img SRC here[/softimg]')
	}catch(e){
		console.log("Could not send to window: " + e);
	}
}

function glossImage () {
	var debug = true;
	try{
		var win = window.dialogArguments || opener || parent || top;
		win.send_to_editor('[glossimg]Place Img SRC here[/glossimg]')
	}catch(e){
		console.log("Could not send to window: " + e);
	}
}
</script>

<div id="tabs">
	<ul>
		<li><a href="#aisis">Aisis Short Codes</a></li>
		<li><a href="#page">Page</a></li>
		<li><a href="#postImages">Post (General)</a></li>
        <li><a href="#postCode">Post (Code)</a></li>
	</ul>
	<div id="aisis">
        <div class="contentSection">
             <div class="title">
                Aisis Short Codes
             </div>
        	<div class="section">
            <p>Aisis short codes are Aisis Specific short codes that help you, the user, get things done faster, easier and more efficient than ever before. 
            We give you examples of what the short code will do, an easy insert into post button and of course what the short code will look like once in your editor.</p>
            
			<p>Aisis Short codes are simply the best thing ever when writing a WordPress post, custom or not, pages and 
            anything else where you might want to integrate short codes.</p>
            </div>
            <div class="middleText">
            	Example:
            </div>
            <pre class="js">
            	[glossyimg] img src [/glossyimg]
            </pre>
            <div class="imgPost centerImage">
                <figure class="post-image glossy">
                    <img src="<?php bloginfo('template_directory');?>/images/bridge.jpg" width="300" height="300"/>
                </figure>
			</div>
        </div>
	</div>
	<div id="page">
        <div class="contentSection">
            <div class="title">
                Page Specific
            </div>
        	<div class="section">
                <p>
                Aisis has an interesting and unique way of displaying images using Css3, html and java script. 
                You don’t have to worry about these things as we deal with 
                them for you. Bellow we show you two of the ways Aisis can 
                deal with images, Soft Images and Glossy Images. To use either just click the "insert into post!"
                </p>
            </div>
            <pre class="js">
            	[glossyimg] img src [/glossyimg]
            </pre>
            <div class="imgPost centerImage">
                <figure class="post-image glossy">
                    <img src="<?php bloginfo('template_directory');?>/images/bridge.jpg" width="300" height="300"/>
                </figure>
			</div>
            <input type="button" value="Insert Into Post!" onclick="softImage()" />
            <br />
            <pre class="js">
            	[glossyimg] img src [/glossyimg]
            </pre>
            <div class="imgPost centerImage">
                <figure class="post-image soft-embossed">
                    <img src="<?php bloginfo('template_directory');?>/images/bridge.jpg" width="300" height="300"/>
                </figure>
			</div>
            <input type="button" value="Insert Into Post!" onclick="glossImage()" />
            <br />
            <pre class="js">
            	[info]This is some info or a summary about said article or paragraph[/info]
            </pre>
            <div class="infoPost">
            	This is some info or a summary about said article or paragraph
            </div>
            <input type="button" value="Insert Into Post!" onclick="glossImage()" />
            <pre class="js">
            	[update]Update Post - Usually at the bottom of the post.[/update]
            </pre>
            <div class="updatePost">
            	This is some info or a summary about said article or paragraph
            </div>
            <input type="button" value="Insert Into Post!" onclick="glossImage()" />            
            <br />
        </div>
	</div>
	<div id="postImages">
         <div class="contentSection">
            <div class="title">
                Post - General Short Codes
            </div>
        	<div class="section">
            </div>
        </div>
	</div>
	<div id="postCode">
         <div class="contentSection">
        	<div class="section">
            	<div class="title">
                	Post - Code
                </div>
            </div>
        </div>
	</div>    
</div>