<?php
$posts = new CoreTheme_AdminPanel_Template_Form_Posts();
$custom = new CoreTheme_AdminPanel_Template_Form_CustomPost();
$social = new CoreTheme_AdminPanel_Template_Form_Social();
$other = new CoreTheme_AdminPanel_Template_Form_Other();

$array = array(
	'method' => 'post',
	'action' => 'options.php',
	'class' => 'form-vertical',
	'settings' => 'aisis_options',
	array(
		'tab' => 'Posts',
		'elements' => array(
			$posts->elements()
		),
	),
	array(
		'tab' => 'Custom Posts',
		'elements' => array(
			$custom->elements()
		),
	),	
	array(
		'tab' => 'Social Links',
		'elements' => array(
			$social->elements()
		),
	),			
	array(
		'tab' => 'Misc. Options',
		'elements' => array(
			$other->elements()
		),
	),				
);

$tabbed_Form = new CoreTheme_Form_TabbedForm($array);
?>

<div class="container">
	<div class="jumbotron subhead">
		<h1>Aisis - <small>Version 1.2</small></h1>
		<p class="lead">A revolution in WordPress theme design!!</p>
		<p class="lead">
			<?php
			$theme = AisisCore_Factory_Pattern::create('AisisCore_Template_Builder');
			
			if(isset($_POST['aisis_reset'])){
				$theme->reset_theme_options();
			}
			
			
			$form = new CoreTheme_AdminPanel_Template_Form_Reset(
				array(
					'action' => '',
					'method' => 'post',
					'class' => 'form-horizontal'
				)
			);
			
			echo $form;
			?>
		</p>
	</div>	
	<?php 
	
	$option = get_option('aisis_success');
	if($option == 'true'){
		echo '<div class="alert alert-success"><strong>SUCCESS!!!!</strong> You have made some killer changes to Aisis! <a href="'.site_url().'">Check it out now!</a></div>';
		update_option('aisis_success', 'false');
	}
	
	echo '<div class="alert alert-info"><strong>Note</strong>: You can make changes to the theme through all the tabs
	and hit save on <strong>any</strong> tab. We will save all changes at once.</div>';
	
	echo $tabbed_Form; 
	
	?>
</div>