<?php 

$update = new CoreTheme_Update(); 
$aisis_template = AisisCore_Factory_Pattern::create('AisisCore_Template_Builder');
?>

<div class="container">
	<div class="jumbotron subhead">
		<h1>Aisis - <small>Version <?php echo $update->get_current_version(); ?></small></h1>
		<p class="lead">Welcome to the update page!</p>
		<p>Best place to be if you are looking to update your version of Aisis!</p>
	</div>	
	<?php 
		if($update->check_for_update()){
			
			?>
			<div class="modified-hero-unit">
				<h2>AISIS <?php echo $update->check_theme_version(); ?> IS HERE!!!!!</h2>
				<p>We have an update for you! <?php echo $update->check_theme_version(); ?> packs a whole new punch with all kinds of new goodies and 
				features and fixes! We are so excited!</p>
                <div class="alert">
                    <strong>Note:</strong> 
                    We suggest that you put your site into maintenance mode.
                    We can also help you with the update, see this 
                    <a href="http://aisis.adambalan.com/tutorials/how-to-update-aisis/">
                        tutorial on how to.
                    </a>
                </div>
                <?php $aisis_template->render_partial('downloadUpdate'); ?>
			</div>
			<?php
		}else{
			echo '<div class="alert alert-success">
                    <strong>Everything is Uptodate!</strong> 
                        You have the latest version of Aisis :D 
                  </div>';
		}
	?>
</div>