<?php 

$update = new CoreTheme_Update(); 
$aisis_template = AisisCore_Factory_Pattern::create('AisisCore_Template_Builder');
?>

<div class="container">
	<div class="jumbotron subhead">
		<h1>Aisis - <small>Version <?php echo $update->get_current_version(); ?></small></h1>
		<p class="lead">Welcome to the update page! Looking to see if you have an update? This is your 
        page!</p>
	</div>	
    <?php 
    $aisis_template->render_partial('updateCheck'); 
    ?>
</div>