<?php 
$template = new CoreTheme_CustomPostTypes_MetaTemplate('aisis_core');
$template->add_meta_template_assets(); 
?>
<div class="aisis_meta_control">
	<br  />
    <p>
    <?php 	
    $post = array(
		'action' => '',
		'method' => 'post',
		'id' => 'test',
		'class' => 'form-horizontal'
	);
	
	echo new CoreTheme_CustomPostTypes_Form_Carousel($post);
	?>
    </p>                
</div>
    
<script language="JavaScript">
	//Upload the image and populate the text box
	jQuery(document).ready(function() {
		jQuery('#upload_image_button').click(function() {
			formfield = jQuery('#aisis_content_img').attr('name');
			tb_show('', 'media-upload.php?type=image&TB_iframe=true');
			return false;
		});
		
		window.send_to_editor = function(html) {
			imgurl = jQuery('img',html).attr('src');
			jQuery('#aisis_content_img').val(imgurl);
			tb_remove();
		}
	});
</script>

<?php $template->remove_meta_template_assets(); ?>