<?php
//get all posts for the post type ae
$aisis_query = array(
	'post_type' => 'ae'
);

query_posts($aisis_query);

//build the sidebar
$sidebar = new AisisSideBar('aisis_core');
$sidebar->sidebar_ae();

?>
<?php while(have_posts()) : the_post();?>
<div id="<?php ae_content_id(); ?>">
	<article class="post clearfix">
		<header>
			<h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<div class="authorInfo">
			Author of this post:
			<a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
			<?php the_author_meta('display_name'); ?></a>
			</div>
		</header>
		<?php if(has_post_thumbnail()){?>
		<div id="postImg">
			<figure class="postImage soft-embossed">
				<?php the_post_thumbnail();?>
			</figure>
		</div>
		<?php }
		the_excerpt(); 
		?>
	</article>
</div>
<?php endwhile;

//Build pagnation
aisis_index_pagination();

aisis_footer();	