<?php 
//Build the sidebar
$aisis_build_index = new AisisSideBar(array('aisis_core', 'aisis_core_bbpress'));
$aisis_build_index->sidebar_index();

while(have_posts()) : the_post();?>
<div id="<?php content_id(); ?>">
	<article class="post clearfix">
		<header>
			<h1 class="postTitle"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1>
			<div class="authorInfo">
			Author of this post:
			<a href="<?php echo get_author_posts_url(get_the_author_meta( 'ID' )); ?>">
			<?php the_author_meta('display_name'); ?></a>, <?php comments_number('0', '1', '%'); ?> comments
			</div>
		</header>
		<?php if(has_post_thumbnail()){?>
		<div id="postImg">
			<figure class="postImage soft-embossed">
				<?php the_post_thumbnail();?>
			</figure>
		</div>
		<?php }
		 the_content('<div class="readMore">More</a>');
		?>
	</article>
</div>	 
<?php endwhile;

//Build Pagnation
aisis_index_pagination();

//Build The footer
aisis_footer();	